// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUserNodeBinding = `-- name: GetUserNodeBinding :one
SELECT
  b.id,
  b.proxy_user_id,
  u.name AS proxy_user_name,
  b.node_id,
  n.name AS node_name,
  b.enabled,
  b.node_quota_bytes,
  b.traffic_multiplier,
  b.disabled_reason,
  b.created_at,
  b.updated_at
FROM user_node_bindings b
JOIN proxy_users u ON u.id = b.proxy_user_id
JOIN nodes n ON n.id = b.node_id
WHERE u.name = ?1 AND n.name = ?2
`

type GetUserNodeBindingParams struct {
	UserName string `json:"user_name"`
	NodeName string `json:"node_name"`
}

type GetUserNodeBindingRow struct {
	ID                string          `json:"id"`
	ProxyUserID       string          `json:"proxy_user_id"`
	ProxyUserName     string          `json:"proxy_user_name"`
	NodeID            string          `json:"node_id"`
	NodeName          string          `json:"node_name"`
	Enabled           int64           `json:"enabled"`
	NodeQuotaBytes    int64           `json:"node_quota_bytes"`
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	DisabledReason    string          `json:"disabled_reason"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

func (q *Queries) GetUserNodeBinding(ctx context.Context, arg GetUserNodeBindingParams) (GetUserNodeBindingRow, error) {
	row := q.db.QueryRowContext(ctx, getUserNodeBinding, arg.UserName, arg.NodeName)
	var i GetUserNodeBindingRow
	err := row.Scan(
		&i.ID,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.NodeID,
		&i.NodeName,
		&i.Enabled,
		&i.NodeQuotaBytes,
		&i.TrafficMultiplier,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserNodeBindings = `-- name: ListUserNodeBindings :many
SELECT
  b.id,
  b.proxy_user_id,
  u.name AS proxy_user_name,
  b.node_id,
  n.name AS node_name,
  b.enabled,
  b.node_quota_bytes,
  b.traffic_multiplier,
  b.disabled_reason,
  b.created_at,
  b.updated_at
FROM user_node_bindings b
JOIN proxy_users u ON u.id = b.proxy_user_id
JOIN nodes n ON n.id = b.node_id
ORDER BY u.name, n.name
`

type ListUserNodeBindingsRow struct {
	ID                string          `json:"id"`
	ProxyUserID       string          `json:"proxy_user_id"`
	ProxyUserName     string          `json:"proxy_user_name"`
	NodeID            string          `json:"node_id"`
	NodeName          string          `json:"node_name"`
	Enabled           int64           `json:"enabled"`
	NodeQuotaBytes    int64           `json:"node_quota_bytes"`
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	DisabledReason    string          `json:"disabled_reason"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

func (q *Queries) ListUserNodeBindings(ctx context.Context) ([]ListUserNodeBindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserNodeBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNodeBindingsRow
	for rows.Next() {
		var i ListUserNodeBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProxyUserID,
			&i.ProxyUserName,
			&i.NodeID,
			&i.NodeName,
			&i.Enabled,
			&i.NodeQuotaBytes,
			&i.TrafficMultiplier,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNodeBindingsByUserName = `-- name: ListUserNodeBindingsByUserName :many
SELECT
  b.id,
  b.proxy_user_id,
  u.name AS proxy_user_name,
  b.node_id,
  n.name AS node_name,
  b.enabled,
  b.node_quota_bytes,
  b.traffic_multiplier,
  b.disabled_reason,
  b.created_at,
  b.updated_at
FROM user_node_bindings b
JOIN proxy_users u ON u.id = b.proxy_user_id
JOIN nodes n ON n.id = b.node_id
WHERE u.name = ?1
ORDER BY u.name, n.name
`

type ListUserNodeBindingsByUserNameRow struct {
	ID                string          `json:"id"`
	ProxyUserID       string          `json:"proxy_user_id"`
	ProxyUserName     string          `json:"proxy_user_name"`
	NodeID            string          `json:"node_id"`
	NodeName          string          `json:"node_name"`
	Enabled           int64           `json:"enabled"`
	NodeQuotaBytes    int64           `json:"node_quota_bytes"`
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	DisabledReason    string          `json:"disabled_reason"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

func (q *Queries) ListUserNodeBindingsByUserName(ctx context.Context, userName string) ([]ListUserNodeBindingsByUserNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserNodeBindingsByUserName, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNodeBindingsByUserNameRow
	for rows.Next() {
		var i ListUserNodeBindingsByUserNameRow
		if err := rows.Scan(
			&i.ID,
			&i.ProxyUserID,
			&i.ProxyUserName,
			&i.NodeID,
			&i.NodeName,
			&i.Enabled,
			&i.NodeQuotaBytes,
			&i.TrafficMultiplier,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserNodeBindingEnabled = `-- name: SetUserNodeBindingEnabled :execrows
UPDATE user_node_bindings
SET
  enabled = ?1,
  disabled_reason = ?2,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?3 AND node_id = ?4
`

type SetUserNodeBindingEnabledParams struct {
	Enabled        int64  `json:"enabled"`
	DisabledReason string `json:"disabled_reason"`
	ProxyUserID    string `json:"proxy_user_id"`
	NodeID         string `json:"node_id"`
}

func (q *Queries) SetUserNodeBindingEnabled(ctx context.Context, arg SetUserNodeBindingEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserNodeBindingEnabled,
		arg.Enabled,
		arg.DisabledReason,
		arg.ProxyUserID,
		arg.NodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserNodeMultiplier = `-- name: SetUserNodeMultiplier :execrows
UPDATE user_node_bindings
SET
  traffic_multiplier = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?2 AND node_id = ?3
`

type SetUserNodeMultiplierParams struct {
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	ProxyUserID       string          `json:"proxy_user_id"`
	NodeID            string          `json:"node_id"`
}

func (q *Queries) SetUserNodeMultiplier(ctx context.Context, arg SetUserNodeMultiplierParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserNodeMultiplier, arg.TrafficMultiplier, arg.ProxyUserID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserNodeQuota = `-- name: SetUserNodeQuota :execrows
UPDATE user_node_bindings
SET
  node_quota_bytes = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?2 AND node_id = ?3
`

type SetUserNodeQuotaParams struct {
	NodeQuotaBytes int64  `json:"node_quota_bytes"`
	ProxyUserID    string `json:"proxy_user_id"`
	NodeID         string `json:"node_id"`
}

func (q *Queries) SetUserNodeQuota(ctx context.Context, arg SetUserNodeQuotaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserNodeQuota, arg.NodeQuotaBytes, arg.ProxyUserID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUserNodeBinding = `-- name: UpsertUserNodeBinding :exec
INSERT INTO user_node_bindings (
  id,
  proxy_user_id,
  node_id,
  enabled,
  disabled_reason
) VALUES (
  ?1,
  ?2,
  ?3,
  1,
  ''
)
ON CONFLICT(proxy_user_id, node_id) DO UPDATE SET
  enabled = 1,
  disabled_reason = '',
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertUserNodeBindingParams struct {
	ID          string `json:"id"`
	ProxyUserID string `json:"proxy_user_id"`
	NodeID      string `json:"node_id"`
}

func (q *Queries) UpsertUserNodeBinding(ctx context.Context, arg UpsertUserNodeBindingParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserNodeBinding, arg.ID, arg.ProxyUserID, arg.NodeID)
	return err
}
