// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config_versions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createConfigVersion = `-- name: CreateConfigVersion :exec
INSERT INTO config_versions (
  id,
  node_id,
  version,
  status,
  config_json,
  config_hash,
  published_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  CASE
    WHEN ?4 = 'published' THEN strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    ELSE NULL
  END
)
`

type CreateConfigVersionParams struct {
	ID         string `json:"id"`
	NodeID     string `json:"node_id"`
	Version    int64  `json:"version"`
	Status     string `json:"status"`
	ConfigJson string `json:"config_json"`
	ConfigHash string `json:"config_hash"`
}

func (q *Queries) CreateConfigVersion(ctx context.Context, arg CreateConfigVersionParams) error {
	_, err := q.db.ExecContext(ctx, createConfigVersion,
		arg.ID,
		arg.NodeID,
		arg.Version,
		arg.Status,
		arg.ConfigJson,
		arg.ConfigHash,
	)
	return err
}

const getConfigVersionByHash = `-- name: GetConfigVersionByHash :one
SELECT
  id,
  node_id,
  version,
  status,
  config_json,
  config_hash,
  created_at,
  published_at
FROM config_versions
WHERE node_id = ?1
  AND config_hash = ?2
`

type GetConfigVersionByHashParams struct {
	NodeID     string `json:"node_id"`
	ConfigHash string `json:"config_hash"`
}

func (q *Queries) GetConfigVersionByHash(ctx context.Context, arg GetConfigVersionByHashParams) (ConfigVersion, error) {
	row := q.db.QueryRowContext(ctx, getConfigVersionByHash, arg.NodeID, arg.ConfigHash)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Version,
		&i.Status,
		&i.ConfigJson,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getConfigVersionByID = `-- name: GetConfigVersionByID :one
SELECT
  id,
  node_id,
  version,
  status,
  config_json,
  config_hash,
  created_at,
  published_at
FROM config_versions
WHERE id = ?1
`

func (q *Queries) GetConfigVersionByID(ctx context.Context, id string) (ConfigVersion, error) {
	row := q.db.QueryRowContext(ctx, getConfigVersionByID, id)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Version,
		&i.Status,
		&i.ConfigJson,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getNodeConfigStatusByNodeName = `-- name: GetNodeConfigStatusByNodeName :one
SELECT
  n.id AS node_id,
  n.name AS node_name,
  s.target_config_version_id,
  target.version AS target_version,
  target.config_hash AS target_config_hash,
  s.current_config_version_id,
  current.version AS current_version,
  current.config_hash AS current_config_hash,
  s.last_apply_status,
  s.last_apply_error,
  s.updated_at
FROM nodes n
LEFT JOIN node_config_status s ON s.node_id = n.id
LEFT JOIN config_versions target ON target.id = s.target_config_version_id
LEFT JOIN config_versions current ON current.id = s.current_config_version_id
WHERE n.name = ?1
`

type GetNodeConfigStatusByNodeNameRow struct {
	NodeID                 string         `json:"node_id"`
	NodeName               string         `json:"node_name"`
	TargetConfigVersionID  sql.NullString `json:"target_config_version_id"`
	TargetVersion          sql.NullInt64  `json:"target_version"`
	TargetConfigHash       sql.NullString `json:"target_config_hash"`
	CurrentConfigVersionID sql.NullString `json:"current_config_version_id"`
	CurrentVersion         sql.NullInt64  `json:"current_version"`
	CurrentConfigHash      sql.NullString `json:"current_config_hash"`
	LastApplyStatus        sql.NullString `json:"last_apply_status"`
	LastApplyError         sql.NullString `json:"last_apply_error"`
	UpdatedAt              sql.NullString `json:"updated_at"`
}

func (q *Queries) GetNodeConfigStatusByNodeName(ctx context.Context, nodeName string) (GetNodeConfigStatusByNodeNameRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeConfigStatusByNodeName, nodeName)
	var i GetNodeConfigStatusByNodeNameRow
	err := row.Scan(
		&i.NodeID,
		&i.NodeName,
		&i.TargetConfigVersionID,
		&i.TargetVersion,
		&i.TargetConfigHash,
		&i.CurrentConfigVersionID,
		&i.CurrentVersion,
		&i.CurrentConfigHash,
		&i.LastApplyStatus,
		&i.LastApplyError,
		&i.UpdatedAt,
	)
	return i, err
}

const getTargetConfigByNodeName = `-- name: GetTargetConfigByNodeName :one
SELECT
  cv.id,
  cv.node_id,
  cv.version,
  cv.status,
  cv.config_json,
  cv.config_hash,
  cv.created_at,
  cv.published_at
FROM node_config_status s
JOIN nodes n ON n.id = s.node_id
JOIN config_versions cv ON cv.id = s.target_config_version_id
WHERE n.name = ?1
`

func (q *Queries) GetTargetConfigByNodeName(ctx context.Context, nodeName string) (ConfigVersion, error) {
	row := q.db.QueryRowContext(ctx, getTargetConfigByNodeName, nodeName)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Version,
		&i.Status,
		&i.ConfigJson,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listConfigVersionsByNode = `-- name: ListConfigVersionsByNode :many
SELECT
  cv.id,
  cv.node_id,
  cv.version,
  cv.status,
  cv.config_json,
  cv.config_hash,
  cv.created_at,
  cv.published_at
FROM config_versions cv
JOIN nodes n ON n.id = cv.node_id
WHERE n.name = ?1
ORDER BY cv.version DESC
`

func (q *Queries) ListConfigVersionsByNode(ctx context.Context, nodeName string) ([]ConfigVersion, error) {
	rows, err := q.db.QueryContext(ctx, listConfigVersionsByNode, nodeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigVersion
	for rows.Next() {
		var i ConfigVersion
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Version,
			&i.Status,
			&i.ConfigJson,
			&i.ConfigHash,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeConfigStatuses = `-- name: ListNodeConfigStatuses :many
SELECT
  n.id AS node_id,
  n.name AS node_name,
  s.target_config_version_id,
  target.version AS target_version,
  target.config_hash AS target_config_hash,
  s.current_config_version_id,
  current.version AS current_version,
  current.config_hash AS current_config_hash,
  s.last_apply_status,
  s.last_apply_error,
  s.updated_at,
  h.reported_at AS latest_heartbeat,
  h.agent_version,
  COALESCE(h.sing_box_version, n.sing_box_version) AS sing_box_version
FROM nodes n
LEFT JOIN node_config_status s ON s.node_id = n.id
LEFT JOIN config_versions target ON target.id = s.target_config_version_id
LEFT JOIN config_versions current ON current.id = s.current_config_version_id
LEFT JOIN node_latest_heartbeats latest ON latest.node_id = n.id
LEFT JOIN node_heartbeats h ON h.id = latest.heartbeat_id
ORDER BY n.name
`

type ListNodeConfigStatusesRow struct {
	NodeID                 string         `json:"node_id"`
	NodeName               string         `json:"node_name"`
	TargetConfigVersionID  sql.NullString `json:"target_config_version_id"`
	TargetVersion          sql.NullInt64  `json:"target_version"`
	TargetConfigHash       sql.NullString `json:"target_config_hash"`
	CurrentConfigVersionID sql.NullString `json:"current_config_version_id"`
	CurrentVersion         sql.NullInt64  `json:"current_version"`
	CurrentConfigHash      sql.NullString `json:"current_config_hash"`
	LastApplyStatus        sql.NullString `json:"last_apply_status"`
	LastApplyError         sql.NullString `json:"last_apply_error"`
	UpdatedAt              sql.NullString `json:"updated_at"`
	LatestHeartbeat        sql.NullString `json:"latest_heartbeat"`
	AgentVersion           sql.NullString `json:"agent_version"`
	SingBoxVersion         string         `json:"sing_box_version"`
}

func (q *Queries) ListNodeConfigStatuses(ctx context.Context) ([]ListNodeConfigStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeConfigStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeConfigStatusesRow
	for rows.Next() {
		var i ListNodeConfigStatusesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.NodeName,
			&i.TargetConfigVersionID,
			&i.TargetVersion,
			&i.TargetConfigHash,
			&i.CurrentConfigVersionID,
			&i.CurrentVersion,
			&i.CurrentConfigHash,
			&i.LastApplyStatus,
			&i.LastApplyError,
			&i.UpdatedAt,
			&i.LatestHeartbeat,
			&i.AgentVersion,
			&i.SingBoxVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConfigVersionPublished = `-- name: MarkConfigVersionPublished :exec
UPDATE config_versions
SET
  status = 'published',
  published_at = COALESCE(published_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE id = ?1
`

func (q *Queries) MarkConfigVersionPublished(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markConfigVersionPublished, id)
	return err
}

const nextConfigVersion = `-- name: NextConfigVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM config_versions
WHERE node_id = ?1
`

func (q *Queries) NextConfigVersion(ctx context.Context, nodeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextConfigVersion, nodeID)
	var next_version int64
	err := row.Scan(&next_version)
	return next_version, err
}

const supersedePublishedConfigVersions = `-- name: SupersedePublishedConfigVersions :exec
UPDATE config_versions
SET status = 'superseded'
WHERE node_id = ?1
  AND status = 'published'
  AND id != ?2
`

type SupersedePublishedConfigVersionsParams struct {
	NodeID string `json:"node_id"`
	KeepID string `json:"keep_id"`
}

func (q *Queries) SupersedePublishedConfigVersions(ctx context.Context, arg SupersedePublishedConfigVersionsParams) error {
	_, err := q.db.ExecContext(ctx, supersedePublishedConfigVersions, arg.NodeID, arg.KeepID)
	return err
}

const updateNodeConfigApplyStatus = `-- name: UpdateNodeConfigApplyStatus :exec
UPDATE node_config_status
SET
  current_config_version_id = CASE
    WHEN ?1 = 'applied' THEN ?2
    ELSE current_config_version_id
  END,
  last_apply_status = ?1,
  last_apply_error = ?3,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?4
`

type UpdateNodeConfigApplyStatusParams struct {
	LastApplyStatus        string         `json:"last_apply_status"`
	CurrentConfigVersionID sql.NullString `json:"current_config_version_id"`
	LastApplyError         string         `json:"last_apply_error"`
	NodeID                 string         `json:"node_id"`
}

func (q *Queries) UpdateNodeConfigApplyStatus(ctx context.Context, arg UpdateNodeConfigApplyStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeConfigApplyStatus,
		arg.LastApplyStatus,
		arg.CurrentConfigVersionID,
		arg.LastApplyError,
		arg.NodeID,
	)
	return err
}

const upsertNodeConfigTarget = `-- name: UpsertNodeConfigTarget :exec
INSERT INTO node_config_status (
  node_id,
  target_config_version_id,
  current_config_version_id,
  last_apply_status,
  last_apply_error
) VALUES (
  ?1,
  ?2,
  NULL,
  'pending',
  ''
)
ON CONFLICT(node_id) DO UPDATE SET
  target_config_version_id = excluded.target_config_version_id,
  last_apply_status = 'pending',
  last_apply_error = '',
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertNodeConfigTargetParams struct {
	NodeID                string         `json:"node_id"`
	TargetConfigVersionID sql.NullString `json:"target_config_version_id"`
}

func (q *Queries) UpsertNodeConfigTarget(ctx context.Context, arg UpsertNodeConfigTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeConfigTarget, arg.NodeID, arg.TargetConfigVersionID)
	return err
}
