// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countConnectionEvents = `-- name: CountConnectionEvents :one
SELECT COUNT(*)
FROM connection_events e
WHERE (?1 = '' OR e.node_id = ?1)
  AND (?2 = '' OR e.proxy_user_id = ?2)
  AND (?3 = '' OR e.bucket_start >= ?3)
  AND (?4 = '' OR e.bucket_start <= ?4)
`

type CountConnectionEventsParams struct {
	NodeID      interface{} `json:"node_id"`
	ProxyUserID interface{} `json:"proxy_user_id"`
	StartTime   interface{} `json:"start_time"`
	EndTime     interface{} `json:"end_time"`
}

func (q *Queries) CountConnectionEvents(ctx context.Context, arg CountConnectionEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConnectionEvents,
		arg.NodeID,
		arg.ProxyUserID,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConnectionReport = `-- name: CreateConnectionReport :exec
INSERT INTO connection_reports (
  id,
  node_id,
  sequence,
  agent_boot_id,
  window_start,
  window_end,
  connections_observed,
  connections_attributed,
  connections_unattributed,
  connections_orphaned,
  stream_resets,
  dropped_buckets,
  bytes_observed,
  bytes_attributed,
  reported_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15
)
`

type CreateConnectionReportParams struct {
	ID                      string `json:"id"`
	NodeID                  string `json:"node_id"`
	Sequence                int64  `json:"sequence"`
	AgentBootID             string `json:"agent_boot_id"`
	WindowStart             string `json:"window_start"`
	WindowEnd               string `json:"window_end"`
	ConnectionsObserved     int64  `json:"connections_observed"`
	ConnectionsAttributed   int64  `json:"connections_attributed"`
	ConnectionsUnattributed int64  `json:"connections_unattributed"`
	ConnectionsOrphaned     int64  `json:"connections_orphaned"`
	StreamResets            int64  `json:"stream_resets"`
	DroppedBuckets          int64  `json:"dropped_buckets"`
	BytesObserved           int64  `json:"bytes_observed"`
	BytesAttributed         int64  `json:"bytes_attributed"`
	ReportedAt              string `json:"reported_at"`
}

func (q *Queries) CreateConnectionReport(ctx context.Context, arg CreateConnectionReportParams) error {
	_, err := q.db.ExecContext(ctx, createConnectionReport,
		arg.ID,
		arg.NodeID,
		arg.Sequence,
		arg.AgentBootID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.ConnectionsObserved,
		arg.ConnectionsAttributed,
		arg.ConnectionsUnattributed,
		arg.ConnectionsOrphaned,
		arg.StreamResets,
		arg.DroppedBuckets,
		arg.BytesObserved,
		arg.BytesAttributed,
		arg.ReportedAt,
	)
	return err
}

const deleteConnectionEventsBefore = `-- name: DeleteConnectionEventsBefore :exec
DELETE FROM connection_events
WHERE bucket_start < ?1
`

// Retention is piggy-backed on ingest exactly like DeleteLogEventsBefore;
// there is no scheduler in this server. bucket_start leads
// idx_connection_events_bucket_host_bytes, so the delete is a bounded range
// scan rather than a full table scan.
func (q *Queries) DeleteConnectionEventsBefore(ctx context.Context, beforeTime string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectionEventsBefore, beforeTime)
	return err
}

const deleteConnectionReportsBefore = `-- name: DeleteConnectionReportsBefore :exec
DELETE FROM connection_reports
WHERE window_end < ?1
`

func (q *Queries) DeleteConnectionReportsBefore(ctx context.Context, beforeTime string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectionReportsBefore, beforeTime)
	return err
}

const deleteNodeConnectionTelemetry = `-- name: DeleteNodeConnectionTelemetry :exec
DELETE FROM node_connection_telemetry
WHERE node_id = ?1
`

func (q *Queries) DeleteNodeConnectionTelemetry(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeConnectionTelemetry, nodeID)
	return err
}

const getConnectionReportBySequence = `-- name: GetConnectionReportBySequence :one
SELECT
  id,
  node_id,
  sequence,
  agent_boot_id,
  window_start,
  window_end,
  reported_at,
  created_at
FROM connection_reports
WHERE node_id = ?1
  AND agent_boot_id = ?2
  AND sequence = ?3
`

type GetConnectionReportBySequenceParams struct {
	NodeID      string `json:"node_id"`
	AgentBootID string `json:"agent_boot_id"`
	Sequence    int64  `json:"sequence"`
}

type GetConnectionReportBySequenceRow struct {
	ID          string `json:"id"`
	NodeID      string `json:"node_id"`
	Sequence    int64  `json:"sequence"`
	AgentBootID string `json:"agent_boot_id"`
	WindowStart string `json:"window_start"`
	WindowEnd   string `json:"window_end"`
	ReportedAt  string `json:"reported_at"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetConnectionReportBySequence(ctx context.Context, arg GetConnectionReportBySequenceParams) (GetConnectionReportBySequenceRow, error) {
	row := q.db.QueryRowContext(ctx, getConnectionReportBySequence, arg.NodeID, arg.AgentBootID, arg.Sequence)
	var i GetConnectionReportBySequenceRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Sequence,
		&i.AgentBootID,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ReportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeConnectionTelemetry = `-- name: GetNodeConnectionTelemetry :one

SELECT
  node_id,
  enabled,
  listen_address,
  listen_port,
  secret,
  rotated_at,
  created_at,
  updated_at
FROM node_connection_telemetry
WHERE node_id = ?1
`

// Connection telemetry from sing-box 1.14's daemon gRPC stream. Opt-in per node
// and off by default: the production fleet runs 1.13, where the service.api
// config block does not parse.
//
// Keep every comment in this file ASCII. sqlc's SQLite parser reports rune
// offsets but slices the source by byte, so a single multi-byte character
// silently corrupts every query after it in the file.
func (q *Queries) GetNodeConnectionTelemetry(ctx context.Context, nodeID string) (NodeConnectionTelemetry, error) {
	row := q.db.QueryRowContext(ctx, getNodeConnectionTelemetry, nodeID)
	var i NodeConnectionTelemetry
	err := row.Scan(
		&i.NodeID,
		&i.Enabled,
		&i.ListenAddress,
		&i.ListenPort,
		&i.Secret,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionEventsPage = `-- name: ListConnectionEventsPage :many
SELECT
  e.id,
  e.node_id,
  e.proxy_user_id,
  e.auth_name,
  e.source_ip,
  e.target_host,
  e.target_port,
  e.domain,
  e.network,
  e.ip_version,
  e.protocol,
  e.inbound,
  e.inbound_type,
  e.rule,
  e.outbound,
  e.outbound_type,
  e.chain,
  e.connections_opened,
  e.connections_closed,
  e.uplink_bytes,
  e.downlink_bytes,
  e.duration_ms_total,
  e.bucket_start,
  e.window_start,
  e.window_end,
  n.name AS node_name,
  COALESCE(u.name, '') AS user_name
FROM connection_events e
JOIN nodes n ON n.id = e.node_id
LEFT JOIN proxy_users u ON u.id = e.proxy_user_id
WHERE (?1 = '' OR e.node_id = ?1)
  AND (?2 = '' OR e.proxy_user_id = ?2)
  AND (?3 = '' OR e.bucket_start >= ?3)
  AND (?4 = '' OR e.bucket_start <= ?4)
ORDER BY e.bucket_start DESC, e.id DESC
LIMIT ?6
OFFSET ?5
`

type ListConnectionEventsPageParams struct {
	NodeID      interface{} `json:"node_id"`
	ProxyUserID interface{} `json:"proxy_user_id"`
	StartTime   interface{} `json:"start_time"`
	EndTime     interface{} `json:"end_time"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type ListConnectionEventsPageRow struct {
	ID                string         `json:"id"`
	NodeID            string         `json:"node_id"`
	ProxyUserID       sql.NullString `json:"proxy_user_id"`
	AuthName          string         `json:"auth_name"`
	SourceIp          string         `json:"source_ip"`
	TargetHost        string         `json:"target_host"`
	TargetPort        int64          `json:"target_port"`
	Domain            string         `json:"domain"`
	Network           string         `json:"network"`
	IpVersion         int64          `json:"ip_version"`
	Protocol          string         `json:"protocol"`
	Inbound           string         `json:"inbound"`
	InboundType       string         `json:"inbound_type"`
	Rule              string         `json:"rule"`
	Outbound          string         `json:"outbound"`
	OutboundType      string         `json:"outbound_type"`
	Chain             string         `json:"chain"`
	ConnectionsOpened int64          `json:"connections_opened"`
	ConnectionsClosed int64          `json:"connections_closed"`
	UplinkBytes       int64          `json:"uplink_bytes"`
	DownlinkBytes     int64          `json:"downlink_bytes"`
	DurationMsTotal   int64          `json:"duration_ms_total"`
	BucketStart       string         `json:"bucket_start"`
	WindowStart       string         `json:"window_start"`
	WindowEnd         string         `json:"window_end"`
	NodeName          string         `json:"node_name"`
	UserName          string         `json:"user_name"`
}

func (q *Queries) ListConnectionEventsPage(ctx context.Context, arg ListConnectionEventsPageParams) ([]ListConnectionEventsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionEventsPage,
		arg.NodeID,
		arg.ProxyUserID,
		arg.StartTime,
		arg.EndTime,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionEventsPageRow
	for rows.Next() {
		var i ListConnectionEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProxyUserID,
			&i.AuthName,
			&i.SourceIp,
			&i.TargetHost,
			&i.TargetPort,
			&i.Domain,
			&i.Network,
			&i.IpVersion,
			&i.Protocol,
			&i.Inbound,
			&i.InboundType,
			&i.Rule,
			&i.Outbound,
			&i.OutboundType,
			&i.Chain,
			&i.ConnectionsOpened,
			&i.ConnectionsClosed,
			&i.UplinkBytes,
			&i.DownlinkBytes,
			&i.DurationMsTotal,
			&i.BucketStart,
			&i.WindowStart,
			&i.WindowEnd,
			&i.NodeName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledConnectionTelemetryNodes = `-- name: ListEnabledConnectionTelemetryNodes :many
SELECT
  t.node_id,
  n.name AS node_name,
  t.listen_address,
  t.listen_port
FROM node_connection_telemetry t
JOIN nodes n ON n.id = t.node_id
WHERE t.enabled = 1
  AND n.deleted_at IS NULL
ORDER BY n.name
`

type ListEnabledConnectionTelemetryNodesRow struct {
	NodeID        string `json:"node_id"`
	NodeName      string `json:"node_name"`
	ListenAddress string `json:"listen_address"`
	ListenPort    int64  `json:"listen_port"`
}

func (q *Queries) ListEnabledConnectionTelemetryNodes(ctx context.Context) ([]ListEnabledConnectionTelemetryNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledConnectionTelemetryNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledConnectionTelemetryNodesRow
	for rows.Next() {
		var i ListEnabledConnectionTelemetryNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.NodeName,
			&i.ListenAddress,
			&i.ListenPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumConnectionBytesByHost = `-- name: SumConnectionBytesByHost :many
SELECT
  e.target_host,
  CAST(SUM(e.uplink_bytes) AS INTEGER) AS uplink_bytes,
  CAST(SUM(e.downlink_bytes) AS INTEGER) AS downlink_bytes,
  CAST(SUM(e.uplink_bytes + e.downlink_bytes) AS INTEGER) AS total_bytes,
  CAST(SUM(e.connections_opened) AS INTEGER) AS connections_opened
FROM connection_events e
WHERE e.bucket_start >= ?1
  AND e.bucket_start <= ?2
  AND (?3 = '' OR e.node_id = ?3)
  AND (?4 = '' OR e.proxy_user_id = ?4)
GROUP BY e.target_host
ORDER BY total_bytes DESC, e.target_host
LIMIT ?5
`

type SumConnectionBytesByHostParams struct {
	StartTime   string      `json:"start_time"`
	EndTime     string      `json:"end_time"`
	NodeID      interface{} `json:"node_id"`
	ProxyUserID interface{} `json:"proxy_user_id"`
	Limit       int64       `json:"limit"`
}

type SumConnectionBytesByHostRow struct {
	TargetHost        string `json:"target_host"`
	UplinkBytes       int64  `json:"uplink_bytes"`
	DownlinkBytes     int64  `json:"downlink_bytes"`
	TotalBytes        int64  `json:"total_bytes"`
	ConnectionsOpened int64  `json:"connections_opened"`
}

// The one read that log_events structurally cannot answer: bytes per
// destination host. Unattributed rows participate, so the totals are complete
// even where `user` was absent on the wire.
func (q *Queries) SumConnectionBytesByHost(ctx context.Context, arg SumConnectionBytesByHostParams) ([]SumConnectionBytesByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, sumConnectionBytesByHost,
		arg.StartTime,
		arg.EndTime,
		arg.NodeID,
		arg.ProxyUserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumConnectionBytesByHostRow
	for rows.Next() {
		var i SumConnectionBytesByHostRow
		if err := rows.Scan(
			&i.TargetHost,
			&i.UplinkBytes,
			&i.DownlinkBytes,
			&i.TotalBytes,
			&i.ConnectionsOpened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumConnectionBytesByUser = `-- name: SumConnectionBytesByUser :many
SELECT
  COALESCE(u.name, '') AS user_name,
  CAST(SUM(e.uplink_bytes) AS INTEGER) AS uplink_bytes,
  CAST(SUM(e.downlink_bytes) AS INTEGER) AS downlink_bytes,
  CAST(SUM(e.uplink_bytes + e.downlink_bytes) AS INTEGER) AS total_bytes,
  CAST(SUM(e.connections_opened) AS INTEGER) AS connections_opened
FROM connection_events e
LEFT JOIN proxy_users u ON u.id = e.proxy_user_id
WHERE e.bucket_start >= ?1
  AND e.bucket_start <= ?2
  AND (?3 = '' OR e.node_id = ?3)
GROUP BY e.proxy_user_id
ORDER BY total_bytes DESC, user_name
LIMIT ?4
`

type SumConnectionBytesByUserParams struct {
	StartTime string      `json:"start_time"`
	EndTime   string      `json:"end_time"`
	NodeID    interface{} `json:"node_id"`
	Limit     int64       `json:"limit"`
}

type SumConnectionBytesByUserRow struct {
	UserName          string `json:"user_name"`
	UplinkBytes       int64  `json:"uplink_bytes"`
	DownlinkBytes     int64  `json:"downlink_bytes"`
	TotalBytes        int64  `json:"total_bytes"`
	ConnectionsOpened int64  `json:"connections_opened"`
}

func (q *Queries) SumConnectionBytesByUser(ctx context.Context, arg SumConnectionBytesByUserParams) ([]SumConnectionBytesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, sumConnectionBytesByUser,
		arg.StartTime,
		arg.EndTime,
		arg.NodeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumConnectionBytesByUserRow
	for rows.Next() {
		var i SumConnectionBytesByUserRow
		if err := rows.Scan(
			&i.UserName,
			&i.UplinkBytes,
			&i.DownlinkBytes,
			&i.TotalBytes,
			&i.ConnectionsOpened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumConnectionCoverage = `-- name: SumConnectionCoverage :one
SELECT
  CAST(COALESCE(SUM(r.connections_observed), 0) AS INTEGER) AS connections_observed,
  CAST(COALESCE(SUM(r.connections_attributed), 0) AS INTEGER) AS connections_attributed,
  CAST(COALESCE(SUM(r.connections_unattributed), 0) AS INTEGER) AS connections_unattributed,
  CAST(COALESCE(SUM(r.connections_orphaned), 0) AS INTEGER) AS connections_orphaned,
  CAST(COALESCE(SUM(r.stream_resets), 0) AS INTEGER) AS stream_resets,
  CAST(COALESCE(SUM(r.dropped_buckets), 0) AS INTEGER) AS dropped_buckets,
  CAST(COALESCE(SUM(r.bytes_observed), 0) AS INTEGER) AS bytes_observed,
  CAST(COALESCE(SUM(r.bytes_attributed), 0) AS INTEGER) AS bytes_attributed,
  COUNT(*) AS reports
FROM connection_reports r
WHERE (?1 = '' OR r.node_id = ?1)
  AND (?2 = '' OR r.window_end >= ?2)
  AND (?3 = '' OR r.window_start <= ?3)
`

type SumConnectionCoverageParams struct {
	NodeID    interface{} `json:"node_id"`
	StartTime interface{} `json:"start_time"`
	EndTime   interface{} `json:"end_time"`
}

type SumConnectionCoverageRow struct {
	ConnectionsObserved     int64 `json:"connections_observed"`
	ConnectionsAttributed   int64 `json:"connections_attributed"`
	ConnectionsUnattributed int64 `json:"connections_unattributed"`
	ConnectionsOrphaned     int64 `json:"connections_orphaned"`
	StreamResets            int64 `json:"stream_resets"`
	DroppedBuckets          int64 `json:"dropped_buckets"`
	BytesObserved           int64 `json:"bytes_observed"`
	BytesAttributed         int64 `json:"bytes_attributed"`
	Reports                 int64 `json:"reports"`
}

// Attribution coverage for a time range. Returned alongside any byte total so
// the UI can state how much of the window is accounted for instead of implying
// the estimate is exact.
func (q *Queries) SumConnectionCoverage(ctx context.Context, arg SumConnectionCoverageParams) (SumConnectionCoverageRow, error) {
	row := q.db.QueryRowContext(ctx, sumConnectionCoverage, arg.NodeID, arg.StartTime, arg.EndTime)
	var i SumConnectionCoverageRow
	err := row.Scan(
		&i.ConnectionsObserved,
		&i.ConnectionsAttributed,
		&i.ConnectionsUnattributed,
		&i.ConnectionsOrphaned,
		&i.StreamResets,
		&i.DroppedBuckets,
		&i.BytesObserved,
		&i.BytesAttributed,
		&i.Reports,
	)
	return i, err
}

const upsertConnectionEvent = `-- name: UpsertConnectionEvent :exec
INSERT INTO connection_events (
  id,
  node_id,
  proxy_user_id,
  auth_name,
  source_ip,
  target_host,
  target_port,
  domain,
  network,
  ip_version,
  protocol,
  inbound,
  inbound_type,
  rule,
  outbound,
  outbound_type,
  chain,
  connections_opened,
  connections_closed,
  uplink_bytes,
  downlink_bytes,
  duration_ms_total,
  aggregate_key,
  bucket_start,
  window_start,
  window_end
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17,
  ?18,
  ?19,
  ?20,
  ?21,
  ?22,
  ?23,
  ?24,
  ?25,
  ?26
) ON CONFLICT(aggregate_key) DO UPDATE SET
  connections_opened = connection_events.connections_opened + excluded.connections_opened,
  connections_closed = connection_events.connections_closed + excluded.connections_closed,
  uplink_bytes = connection_events.uplink_bytes + excluded.uplink_bytes,
  downlink_bytes = connection_events.downlink_bytes + excluded.downlink_bytes,
  duration_ms_total = connection_events.duration_ms_total + excluded.duration_ms_total,
  proxy_user_id = COALESCE(connection_events.proxy_user_id, excluded.proxy_user_id),
  window_start = MIN(connection_events.window_start, excluded.window_start),
  window_end = MAX(connection_events.window_end, excluded.window_end),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertConnectionEventParams struct {
	ID                string         `json:"id"`
	NodeID            string         `json:"node_id"`
	ProxyUserID       sql.NullString `json:"proxy_user_id"`
	AuthName          string         `json:"auth_name"`
	SourceIp          string         `json:"source_ip"`
	TargetHost        string         `json:"target_host"`
	TargetPort        int64          `json:"target_port"`
	Domain            string         `json:"domain"`
	Network           string         `json:"network"`
	IpVersion         int64          `json:"ip_version"`
	Protocol          string         `json:"protocol"`
	Inbound           string         `json:"inbound"`
	InboundType       string         `json:"inbound_type"`
	Rule              string         `json:"rule"`
	Outbound          string         `json:"outbound"`
	OutboundType      string         `json:"outbound_type"`
	Chain             string         `json:"chain"`
	ConnectionsOpened int64          `json:"connections_opened"`
	ConnectionsClosed int64          `json:"connections_closed"`
	UplinkBytes       int64          `json:"uplink_bytes"`
	DownlinkBytes     int64          `json:"downlink_bytes"`
	DurationMsTotal   int64          `json:"duration_ms_total"`
	AggregateKey      string         `json:"aggregate_key"`
	BucketStart       string         `json:"bucket_start"`
	WindowStart       string         `json:"window_start"`
	WindowEnd         string         `json:"window_end"`
}

// Buckets merge across reports: a connection that stays open across two report
// windows lands in the same (dimensions, bucket_start) row twice. Summing on
// conflict is what keeps a long-lived session from being split into fragments,
// and it is why report_id is not carried on the row: after a merge it would
// name only one of several contributing reports.
func (q *Queries) UpsertConnectionEvent(ctx context.Context, arg UpsertConnectionEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnectionEvent,
		arg.ID,
		arg.NodeID,
		arg.ProxyUserID,
		arg.AuthName,
		arg.SourceIp,
		arg.TargetHost,
		arg.TargetPort,
		arg.Domain,
		arg.Network,
		arg.IpVersion,
		arg.Protocol,
		arg.Inbound,
		arg.InboundType,
		arg.Rule,
		arg.Outbound,
		arg.OutboundType,
		arg.Chain,
		arg.ConnectionsOpened,
		arg.ConnectionsClosed,
		arg.UplinkBytes,
		arg.DownlinkBytes,
		arg.DurationMsTotal,
		arg.AggregateKey,
		arg.BucketStart,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}

const upsertNodeConnectionTelemetry = `-- name: UpsertNodeConnectionTelemetry :exec
INSERT INTO node_connection_telemetry (
  node_id,
  enabled,
  listen_address,
  listen_port,
  secret,
  rotated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6
) ON CONFLICT(node_id) DO UPDATE SET
  enabled = excluded.enabled,
  listen_address = excluded.listen_address,
  listen_port = excluded.listen_port,
  secret = excluded.secret,
  rotated_at = excluded.rotated_at,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertNodeConnectionTelemetryParams struct {
	NodeID        string         `json:"node_id"`
	Enabled       int64          `json:"enabled"`
	ListenAddress string         `json:"listen_address"`
	ListenPort    int64          `json:"listen_port"`
	Secret        string         `json:"secret"`
	RotatedAt     sql.NullString `json:"rotated_at"`
}

func (q *Queries) UpsertNodeConnectionTelemetry(ctx context.Context, arg UpsertNodeConnectionTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeConnectionTelemetry,
		arg.NodeID,
		arg.Enabled,
		arg.ListenAddress,
		arg.ListenPort,
		arg.Secret,
		arg.RotatedAt,
	)
	return err
}
