// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletion.sql

package sqlc

import (
	"context"
	"database/sql"
)

const archivePathAccesses = `-- name: ArchivePathAccesses :exec
UPDATE path_accesses SET enabled=0, deleted_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'), updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE path_id=?1 AND deleted_at IS NULL
`

func (q *Queries) ArchivePathAccesses(ctx context.Context, pathID string) error {
	_, err := q.db.ExecContext(ctx, archivePathAccesses, pathID)
	return err
}

const archiveRetiredProxyCredentials = `-- name: ArchiveRetiredProxyCredentials :exec
UPDATE proxy_accesses SET enabled=0, deleted_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'), updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE deleted_at IS NULL AND proxy_id IN (
 SELECT p.id FROM proxies p JOIN nodes n ON n.id=p.node_id WHERE p.deleted_at IS NOT NULL OR n.deleted_at IS NOT NULL
)
`

func (q *Queries) ArchiveRetiredProxyCredentials(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, archiveRetiredProxyCredentials)
	return err
}

const disableRetiredEndpoints = `-- name: DisableRetiredEndpoints :exec
UPDATE endpoints SET enabled=0, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE enabled=1 AND proxy_id IN (
 SELECT p.id FROM proxies p JOIN nodes n ON n.id=p.node_id WHERE p.deleted_at IS NOT NULL OR n.deleted_at IS NOT NULL
)
`

func (q *Queries) DisableRetiredEndpoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, disableRetiredEndpoints)
	return err
}

const disableRetiredNodeBindings = `-- name: DisableRetiredNodeBindings :exec
UPDATE user_node_bindings SET enabled=0, disabled_reason='node_deleted', updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE enabled=1 AND node_id IN (SELECT id FROM nodes WHERE deleted_at IS NOT NULL)
`

func (q *Queries) DisableRetiredNodeBindings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, disableRetiredNodeBindings)
	return err
}

const listDeletionAccesses = `-- name: ListDeletionAccesses :many
SELECT a.id,a.path_id,a.proxy_user_id,a.enabled,a.deleted_at,u.name AS user_name FROM path_accesses a JOIN proxy_users u ON u.id=a.proxy_user_id
`

type ListDeletionAccessesRow struct {
	ID          string         `json:"id"`
	PathID      string         `json:"path_id"`
	ProxyUserID string         `json:"proxy_user_id"`
	Enabled     int64          `json:"enabled"`
	DeletedAt   sql.NullString `json:"deleted_at"`
	UserName    string         `json:"user_name"`
}

func (q *Queries) ListDeletionAccesses(ctx context.Context) ([]ListDeletionAccessesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletionAccesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletionAccessesRow
	for rows.Next() {
		var i ListDeletionAccessesRow
		if err := rows.Scan(
			&i.ID,
			&i.PathID,
			&i.ProxyUserID,
			&i.Enabled,
			&i.DeletedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletionCredentials = `-- name: ListDeletionCredentials :many
SELECT a.id,a.proxy_id,a.proxy_user_id,a.enabled,a.deleted_at,u.name AS user_name FROM proxy_accesses a JOIN proxy_users u ON u.id=a.proxy_user_id
`

type ListDeletionCredentialsRow struct {
	ID          string         `json:"id"`
	ProxyID     string         `json:"proxy_id"`
	ProxyUserID string         `json:"proxy_user_id"`
	Enabled     int64          `json:"enabled"`
	DeletedAt   sql.NullString `json:"deleted_at"`
	UserName    string         `json:"user_name"`
}

func (q *Queries) ListDeletionCredentials(ctx context.Context) ([]ListDeletionCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletionCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletionCredentialsRow
	for rows.Next() {
		var i ListDeletionCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProxyID,
			&i.ProxyUserID,
			&i.Enabled,
			&i.DeletedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletionProxies = `-- name: ListDeletionProxies :many
SELECT p.id,p.node_id,p.name,p.deleted_at,n.deleted_at AS node_deleted_at FROM proxies p JOIN nodes n ON n.id=p.node_id
`

type ListDeletionProxiesRow struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	Name          string         `json:"name"`
	DeletedAt     sql.NullString `json:"deleted_at"`
	NodeDeletedAt sql.NullString `json:"node_deleted_at"`
}

func (q *Queries) ListDeletionProxies(ctx context.Context) ([]ListDeletionProxiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletionProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletionProxiesRow
	for rows.Next() {
		var i ListDeletionProxiesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.DeletedAt,
			&i.NodeDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathAccessUsersIncludingDeleted = `-- name: ListPathAccessUsersIncludingDeleted :many
SELECT DISTINCT proxy_user_id FROM path_accesses WHERE path_id=?1 AND deleted_at IS NULL
`

func (q *Queries) ListPathAccessUsersIncludingDeleted(ctx context.Context, pathID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPathAccessUsersIncludingDeleted, pathID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var proxy_user_id string
		if err := rows.Scan(&proxy_user_id); err != nil {
			return nil, err
		}
		items = append(items, proxy_user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetiredResourcePaths = `-- name: ListRetiredResourcePaths :many
WITH RECURSIVE affected_paths(id) AS (
 SELECT t.id FROM paths t JOIN endpoints e ON e.id=t.endpoint_id
 JOIN proxies p ON p.id=e.proxy_id JOIN nodes n ON n.id=p.node_id
 WHERE p.deleted_at IS NOT NULL OR n.deleted_at IS NOT NULL
 UNION
 SELECT t.id FROM paths t JOIN affected_paths a ON t.dialer_path_id=a.id
)
SELECT id FROM affected_paths
`

func (q *Queries) ListRetiredResourcePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRetiredResourcePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProxyEndpoints = `-- name: RestoreProxyEndpoints :exec
UPDATE endpoints SET enabled=1, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE proxy_id=?1 AND enabled=0
`

func (q *Queries) RestoreProxyEndpoints(ctx context.Context, proxyID string) error {
	_, err := q.db.ExecContext(ctx, restoreProxyEndpoints, proxyID)
	return err
}
