// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_service_overrides.sql

package sqlc

import (
	"context"
)

const deleteDomainServiceOverride = `-- name: DeleteDomainServiceOverride :exec
DELETE FROM domain_service_overrides
WHERE suffix = ?1
`

func (q *Queries) DeleteDomainServiceOverride(ctx context.Context, suffix string) error {
	_, err := q.db.ExecContext(ctx, deleteDomainServiceOverride, suffix)
	return err
}

const getDomainServiceOverride = `-- name: GetDomainServiceOverride :one
SELECT
  suffix,
  service,
  label,
  category,
  created_at,
  updated_at
FROM domain_service_overrides
WHERE suffix = ?1
`

func (q *Queries) GetDomainServiceOverride(ctx context.Context, suffix string) (DomainServiceOverride, error) {
	row := q.db.QueryRowContext(ctx, getDomainServiceOverride, suffix)
	var i DomainServiceOverride
	err := row.Scan(
		&i.Suffix,
		&i.Service,
		&i.Label,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainServiceOverrides = `-- name: ListDomainServiceOverrides :many
SELECT
  suffix,
  service,
  label,
  category,
  created_at,
  updated_at
FROM domain_service_overrides
ORDER BY suffix
`

func (q *Queries) ListDomainServiceOverrides(ctx context.Context) ([]DomainServiceOverride, error) {
	rows, err := q.db.QueryContext(ctx, listDomainServiceOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainServiceOverride
	for rows.Next() {
		var i DomainServiceOverride
		if err := rows.Scan(
			&i.Suffix,
			&i.Service,
			&i.Label,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDomainServiceOverride = `-- name: UpsertDomainServiceOverride :exec
INSERT INTO domain_service_overrides (
  suffix,
  service,
  label,
  category
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4
) ON CONFLICT(suffix) DO UPDATE SET
  service = excluded.service,
  label = excluded.label,
  category = excluded.category,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertDomainServiceOverrideParams struct {
	Suffix   string `json:"suffix"`
	Service  string `json:"service"`
	Label    string `json:"label"`
	Category string `json:"category"`
}

func (q *Queries) UpsertDomainServiceOverride(ctx context.Context, arg UpsertDomainServiceOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertDomainServiceOverride,
		arg.Suffix,
		arg.Service,
		arg.Label,
		arg.Category,
	)
	return err
}
