// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package sqlc

import (
	"context"
)

const countEndpointsByHostID = `-- name: CountEndpointsByHostID :one
SELECT COUNT(*) FROM endpoints WHERE host_id = ?1
`

func (q *Queries) CountEndpointsByHostID(ctx context.Context, hostID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEndpointsByHostID, hostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEndpoint = `-- name: CreateEndpoint :exec
INSERT INTO endpoints (id, proxy_id, host_id, enabled)
VALUES (?1, ?2, ?3, ?4)
`

type CreateEndpointParams struct {
	ID      string `json:"id"`
	ProxyID string `json:"proxy_id"`
	HostID  string `json:"host_id"`
	Enabled int64  `json:"enabled"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) error {
	_, err := q.db.ExecContext(ctx, createEndpoint,
		arg.ID,
		arg.ProxyID,
		arg.HostID,
		arg.Enabled,
	)
	return err
}

const deleteEndpoint = `-- name: DeleteEndpoint :execrows
DELETE FROM endpoints WHERE id = ?1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEndpoint, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, proxy_id, host_id, enabled, created_at, updated_at FROM endpoints WHERE id = ?1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpointByID, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProxyID,
		&i.HostID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByProxyHost = `-- name: GetEndpointByProxyHost :one
SELECT id, proxy_id, host_id, enabled, created_at, updated_at FROM endpoints
WHERE proxy_id = ?1 AND host_id = ?2
`

type GetEndpointByProxyHostParams struct {
	ProxyID string `json:"proxy_id"`
	HostID  string `json:"host_id"`
}

func (q *Queries) GetEndpointByProxyHost(ctx context.Context, arg GetEndpointByProxyHostParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpointByProxyHost, arg.ProxyID, arg.HostID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProxyID,
		&i.HostID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, proxy_id, host_id, enabled, created_at, updated_at FROM endpoints ORDER BY created_at, id
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProxyID,
			&i.HostID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsByProxyID = `-- name: ListEndpointsByProxyID :many
SELECT id, proxy_id, host_id, enabled, created_at, updated_at FROM endpoints WHERE proxy_id = ?1 ORDER BY created_at, id
`

func (q *Queries) ListEndpointsByProxyID(ctx context.Context, proxyID string) ([]Endpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpointsByProxyID, proxyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProxyID,
			&i.HostID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEndpointEnabled = `-- name: SetEndpointEnabled :execrows
UPDATE endpoints
SET enabled = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
`

type SetEndpointEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) SetEndpointEnabled(ctx context.Context, arg SetEndpointEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setEndpointEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
