// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heartbeats.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createNodeHeartbeat = `-- name: CreateNodeHeartbeat :exec
INSERT INTO node_heartbeats (
  id,
  node_id,
  agent_version,
  sing_box_version,
  status,
  memory_bytes,
  rx_bytes,
  tx_bytes,
  payload_json,
  reported_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
`

type CreateNodeHeartbeatParams struct {
	ID             string `json:"id"`
	NodeID         string `json:"node_id"`
	AgentVersion   string `json:"agent_version"`
	SingBoxVersion string `json:"sing_box_version"`
	Status         string `json:"status"`
	MemoryBytes    int64  `json:"memory_bytes"`
	RxBytes        int64  `json:"rx_bytes"`
	TxBytes        int64  `json:"tx_bytes"`
	PayloadJson    string `json:"payload_json"`
	ReportedAt     string `json:"reported_at"`
}

func (q *Queries) CreateNodeHeartbeat(ctx context.Context, arg CreateNodeHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, createNodeHeartbeat,
		arg.ID,
		arg.NodeID,
		arg.AgentVersion,
		arg.SingBoxVersion,
		arg.Status,
		arg.MemoryBytes,
		arg.RxBytes,
		arg.TxBytes,
		arg.PayloadJson,
		arg.ReportedAt,
	)
	return err
}

const latestNodeHeartbeatByNodeName = `-- name: LatestNodeHeartbeatByNodeName :one
SELECT
  h.id,
  h.node_id,
  h.agent_version,
  h.sing_box_version,
  h.status,
  h.memory_bytes,
  h.rx_bytes,
  h.tx_bytes,
  h.payload_json,
  h.reported_at,
  h.created_at
FROM node_heartbeats h
JOIN nodes n ON n.id = h.node_id
WHERE n.name = ?1
ORDER BY h.created_at DESC
LIMIT 1
`

func (q *Queries) LatestNodeHeartbeatByNodeName(ctx context.Context, nodeName string) (NodeHeartbeat, error) {
	row := q.db.QueryRowContext(ctx, latestNodeHeartbeatByNodeName, nodeName)
	var i NodeHeartbeat
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.AgentVersion,
		&i.SingBoxVersion,
		&i.Status,
		&i.MemoryBytes,
		&i.RxBytes,
		&i.TxBytes,
		&i.PayloadJson,
		&i.ReportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchNodeSeen = `-- name: TouchNodeSeen :exec
UPDATE nodes
SET
  last_seen_at = ?1,
  sing_box_version = ?2,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?3
`

type TouchNodeSeenParams struct {
	LastSeenAt     sql.NullString `json:"last_seen_at"`
	SingBoxVersion string         `json:"sing_box_version"`
	NodeID         string         `json:"node_id"`
}

func (q *Queries) TouchNodeSeen(ctx context.Context, arg TouchNodeSeenParams) error {
	_, err := q.db.ExecContext(ctx, touchNodeSeen, arg.LastSeenAt, arg.SingBoxVersion, arg.NodeID)
	return err
}
