// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countLogEvents = `-- name: CountLogEvents :one
SELECT COUNT(*)
FROM log_events e
JOIN nodes n ON n.id = e.node_id
JOIN proxy_users u ON u.id = e.proxy_user_id
WHERE e.proxy_user_id IS NOT NULL
  AND (?1 = '' OR n.name = ?1)
  AND (?2 = '' OR u.name = ?2)
  AND (?3 = '' OR e.window_end >= ?3)
  AND (?4 = '' OR e.window_start <= ?4)
`

type CountLogEventsParams struct {
	NodeName  interface{} `json:"node_name"`
	UserName  interface{} `json:"user_name"`
	StartTime interface{} `json:"start_time"`
	EndTime   interface{} `json:"end_time"`
}

func (q *Queries) CountLogEvents(ctx context.Context, arg CountLogEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLogEvents,
		arg.NodeName,
		arg.UserName,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLogEvent = `-- name: CreateLogEvent :exec
INSERT INTO log_events (
  id,
  node_id,
  proxy_user_id,
  auth_name,
  source_ip,
  target_host,
  target_port,
  action,
  raw_message,
  count,
  aggregate_key,
  window_start,
  window_end
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13
) ON CONFLICT(aggregate_key) WHERE aggregate_key <> '' DO UPDATE SET
  count = log_events.count + excluded.count,
  window_start = CASE
    WHEN excluded.window_start < log_events.window_start THEN excluded.window_start
    ELSE log_events.window_start
  END,
  window_end = CASE
    WHEN excluded.window_end > log_events.window_end THEN excluded.window_end
    ELSE log_events.window_end
  END,
  raw_message = CASE
    WHEN log_events.raw_message = '' THEN excluded.raw_message
    ELSE log_events.raw_message
  END,
  created_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type CreateLogEventParams struct {
	ID           string         `json:"id"`
	NodeID       string         `json:"node_id"`
	ProxyUserID  sql.NullString `json:"proxy_user_id"`
	AuthName     string         `json:"auth_name"`
	SourceIp     string         `json:"source_ip"`
	TargetHost   string         `json:"target_host"`
	TargetPort   int64          `json:"target_port"`
	Action       string         `json:"action"`
	RawMessage   string         `json:"raw_message"`
	Count        int64          `json:"count"`
	AggregateKey string         `json:"aggregate_key"`
	WindowStart  string         `json:"window_start"`
	WindowEnd    string         `json:"window_end"`
}

func (q *Queries) CreateLogEvent(ctx context.Context, arg CreateLogEventParams) error {
	_, err := q.db.ExecContext(ctx, createLogEvent,
		arg.ID,
		arg.NodeID,
		arg.ProxyUserID,
		arg.AuthName,
		arg.SourceIp,
		arg.TargetHost,
		arg.TargetPort,
		arg.Action,
		arg.RawMessage,
		arg.Count,
		arg.AggregateKey,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}

const deleteLogEventsBefore = `-- name: DeleteLogEventsBefore :exec
DELETE FROM log_events
WHERE window_end < ?1
`

func (q *Queries) DeleteLogEventsBefore(ctx context.Context, beforeTime string) error {
	_, err := q.db.ExecContext(ctx, deleteLogEventsBefore, beforeTime)
	return err
}

const getProxyUserIDByNodeAuthName = `-- name: GetProxyUserIDByNodeAuthName :one
SELECT c.proxy_user_id
FROM proxy_accesses c
JOIN proxies p ON p.id = c.proxy_id
JOIN nodes n ON n.id = p.node_id
WHERE n.name = ?1
  AND c.auth_name = ?2
`

type GetProxyUserIDByNodeAuthNameParams struct {
	NodeName string `json:"node_name"`
	AuthName string `json:"auth_name"`
}

func (q *Queries) GetProxyUserIDByNodeAuthName(ctx context.Context, arg GetProxyUserIDByNodeAuthNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProxyUserIDByNodeAuthName, arg.NodeName, arg.AuthName)
	var proxy_user_id string
	err := row.Scan(&proxy_user_id)
	return proxy_user_id, err
}

const listLogEventsPage = `-- name: ListLogEventsPage :many
SELECT
  e.id,
  e.node_id,
  e.proxy_user_id,
  e.auth_name,
  e.source_ip,
  e.target_host,
  e.target_port,
  e.action,
  e.raw_message,
  e.count,
  e.aggregate_key,
  e.window_start,
  e.window_end,
  e.created_at,
  n.name AS node_name,
  u.name AS user_name
FROM log_events e
JOIN nodes n ON n.id = e.node_id
JOIN proxy_users u ON u.id = e.proxy_user_id
WHERE e.proxy_user_id IS NOT NULL
  AND (?1 = '' OR n.name = ?1)
  AND (?2 = '' OR u.name = ?2)
  AND (?3 = '' OR e.window_end >= ?3)
  AND (?4 = '' OR e.window_start <= ?4)
ORDER BY e.created_at DESC, e.window_end DESC, e.id DESC
LIMIT ?6
OFFSET ?5
`

type ListLogEventsPageParams struct {
	NodeName  interface{} `json:"node_name"`
	UserName  interface{} `json:"user_name"`
	StartTime interface{} `json:"start_time"`
	EndTime   interface{} `json:"end_time"`
	Offset    int64       `json:"offset"`
	Limit     int64       `json:"limit"`
}

type ListLogEventsPageRow struct {
	ID           string         `json:"id"`
	NodeID       string         `json:"node_id"`
	ProxyUserID  sql.NullString `json:"proxy_user_id"`
	AuthName     string         `json:"auth_name"`
	SourceIp     string         `json:"source_ip"`
	TargetHost   string         `json:"target_host"`
	TargetPort   int64          `json:"target_port"`
	Action       string         `json:"action"`
	RawMessage   string         `json:"raw_message"`
	Count        int64          `json:"count"`
	AggregateKey string         `json:"aggregate_key"`
	WindowStart  string         `json:"window_start"`
	WindowEnd    string         `json:"window_end"`
	CreatedAt    string         `json:"created_at"`
	NodeName     string         `json:"node_name"`
	UserName     string         `json:"user_name"`
}

func (q *Queries) ListLogEventsPage(ctx context.Context, arg ListLogEventsPageParams) ([]ListLogEventsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogEventsPage,
		arg.NodeName,
		arg.UserName,
		arg.StartTime,
		arg.EndTime,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventsPageRow
	for rows.Next() {
		var i ListLogEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProxyUserID,
			&i.AuthName,
			&i.SourceIp,
			&i.TargetHost,
			&i.TargetPort,
			&i.Action,
			&i.RawMessage,
			&i.Count,
			&i.AggregateKey,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
			&i.NodeName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLogEvents = `-- name: ListRecentLogEvents :many
SELECT
  e.id,
  e.node_id,
  e.proxy_user_id,
  e.auth_name,
  e.source_ip,
  e.target_host,
  e.target_port,
  e.action,
  e.raw_message,
  e.count,
  e.aggregate_key,
  e.window_start,
  e.window_end,
  e.created_at
FROM log_events e
WHERE e.proxy_user_id IS NOT NULL
ORDER BY e.created_at DESC, e.window_end DESC, e.id DESC
LIMIT ?1
`

func (q *Queries) ListRecentLogEvents(ctx context.Context, limit int64) ([]LogEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLogEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEvent
	for rows.Next() {
		var i LogEvent
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProxyUserID,
			&i.AuthName,
			&i.SourceIp,
			&i.TargetHost,
			&i.TargetPort,
			&i.Action,
			&i.RawMessage,
			&i.Count,
			&i.AggregateKey,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLogEventsByNode = `-- name: ListRecentLogEventsByNode :many
SELECT
  e.id,
  e.node_id,
  e.proxy_user_id,
  e.auth_name,
  e.source_ip,
  e.target_host,
  e.target_port,
  e.action,
  e.raw_message,
  e.count,
  e.aggregate_key,
  e.window_start,
  e.window_end,
  e.created_at
FROM log_events e
JOIN nodes n ON n.id = e.node_id
WHERE n.name = ?1
  AND e.proxy_user_id IS NOT NULL
ORDER BY e.created_at DESC, e.window_end DESC, e.id DESC
LIMIT ?2
`

type ListRecentLogEventsByNodeParams struct {
	NodeName string `json:"node_name"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListRecentLogEventsByNode(ctx context.Context, arg ListRecentLogEventsByNodeParams) ([]LogEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLogEventsByNode, arg.NodeName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEvent
	for rows.Next() {
		var i LogEvent
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProxyUserID,
			&i.AuthName,
			&i.SourceIp,
			&i.TargetHost,
			&i.TargetPort,
			&i.Action,
			&i.RawMessage,
			&i.Count,
			&i.AggregateKey,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLogEventsByUser = `-- name: ListRecentLogEventsByUser :many
SELECT
  e.id,
  e.node_id,
  e.proxy_user_id,
  e.auth_name,
  e.source_ip,
  e.target_host,
  e.target_port,
  e.action,
  e.raw_message,
  e.count,
  e.aggregate_key,
  e.window_start,
  e.window_end,
  e.created_at
FROM log_events e
JOIN proxy_users u ON u.id = e.proxy_user_id
WHERE u.name = ?1
ORDER BY e.created_at DESC, e.window_end DESC, e.id DESC
LIMIT ?2
`

type ListRecentLogEventsByUserParams struct {
	UserName string `json:"user_name"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListRecentLogEventsByUser(ctx context.Context, arg ListRecentLogEventsByUserParams) ([]LogEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLogEventsByUser, arg.UserName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEvent
	for rows.Next() {
		var i LogEvent
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProxyUserID,
			&i.AuthName,
			&i.SourceIp,
			&i.TargetHost,
			&i.TargetPort,
			&i.Action,
			&i.RawMessage,
			&i.Count,
			&i.AggregateKey,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
