// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mihomo_profile_subscription_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMihomoProfileSubscriptionToken = `-- name: CreateMihomoProfileSubscriptionToken :exec
INSERT INTO mihomo_profile_subscription_tokens (id, profile_id, token)
VALUES (?1, ?2, ?3)
`

type CreateMihomoProfileSubscriptionTokenParams struct {
	ID        string `json:"id"`
	ProfileID string `json:"profile_id"`
	Token     string `json:"token"`
}

func (q *Queries) CreateMihomoProfileSubscriptionToken(ctx context.Context, arg CreateMihomoProfileSubscriptionTokenParams) error {
	_, err := q.db.ExecContext(ctx, createMihomoProfileSubscriptionToken, arg.ID, arg.ProfileID, arg.Token)
	return err
}

const getActiveMihomoProfileSubscriptionToken = `-- name: GetActiveMihomoProfileSubscriptionToken :one
SELECT
  t.id, t.profile_id, p.name AS profile_name,
  p.proxy_user_id, u.name AS proxy_user_name,
  t.token, t.created_at, t.last_used_at, t.revoked_at
FROM mihomo_profile_subscription_tokens t
JOIN mihomo_profiles p ON p.id = t.profile_id
JOIN proxy_users u ON u.id = p.proxy_user_id
WHERE t.profile_id = ?1
  AND u.deleted_at IS NULL
  AND t.revoked_at IS NULL
`

type GetActiveMihomoProfileSubscriptionTokenRow struct {
	ID            string         `json:"id"`
	ProfileID     string         `json:"profile_id"`
	ProfileName   string         `json:"profile_name"`
	ProxyUserID   sql.NullString `json:"proxy_user_id"`
	ProxyUserName string         `json:"proxy_user_name"`
	Token         string         `json:"token"`
	CreatedAt     string         `json:"created_at"`
	LastUsedAt    sql.NullString `json:"last_used_at"`
	RevokedAt     sql.NullString `json:"revoked_at"`
}

func (q *Queries) GetActiveMihomoProfileSubscriptionToken(ctx context.Context, profileID string) (GetActiveMihomoProfileSubscriptionTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveMihomoProfileSubscriptionToken, profileID)
	var i GetActiveMihomoProfileSubscriptionTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ProfileName,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.Token,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveMihomoProfileSubscriptionTokenByValue = `-- name: GetActiveMihomoProfileSubscriptionTokenByValue :one
SELECT
  t.id, t.profile_id, p.name AS profile_name,
  p.proxy_user_id, u.name AS proxy_user_name,
  t.token, t.created_at, t.last_used_at, t.revoked_at
FROM mihomo_profile_subscription_tokens t
JOIN mihomo_profiles p ON p.id = t.profile_id
JOIN proxy_users u ON u.id = p.proxy_user_id
WHERE t.token = ?1
  AND u.deleted_at IS NULL
  AND t.revoked_at IS NULL
`

type GetActiveMihomoProfileSubscriptionTokenByValueRow struct {
	ID            string         `json:"id"`
	ProfileID     string         `json:"profile_id"`
	ProfileName   string         `json:"profile_name"`
	ProxyUserID   sql.NullString `json:"proxy_user_id"`
	ProxyUserName string         `json:"proxy_user_name"`
	Token         string         `json:"token"`
	CreatedAt     string         `json:"created_at"`
	LastUsedAt    sql.NullString `json:"last_used_at"`
	RevokedAt     sql.NullString `json:"revoked_at"`
}

func (q *Queries) GetActiveMihomoProfileSubscriptionTokenByValue(ctx context.Context, token string) (GetActiveMihomoProfileSubscriptionTokenByValueRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveMihomoProfileSubscriptionTokenByValue, token)
	var i GetActiveMihomoProfileSubscriptionTokenByValueRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ProfileName,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.Token,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markMihomoProfileSubscriptionTokenUsed = `-- name: MarkMihomoProfileSubscriptionTokenUsed :exec
UPDATE mihomo_profile_subscription_tokens
SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) MarkMihomoProfileSubscriptionTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markMihomoProfileSubscriptionTokenUsed, id)
	return err
}

const revokeActiveMihomoProfileSubscriptionToken = `-- name: RevokeActiveMihomoProfileSubscriptionToken :execrows
UPDATE mihomo_profile_subscription_tokens
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE profile_id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeActiveMihomoProfileSubscriptionToken(ctx context.Context, profileID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeActiveMihomoProfileSubscriptionToken, profileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
