// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mihomo_profiles.sql

package sqlc

import (
	"context"
	"database/sql"
)

const assignMihomoProfileToUser = `-- name: AssignMihomoProfileToUser :exec
INSERT INTO proxy_user_mihomo_profiles (proxy_user_id, profile_id)
VALUES (?1, ?2)
ON CONFLICT(proxy_user_id) DO UPDATE SET
  profile_id = excluded.profile_id,
  assigned_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type AssignMihomoProfileToUserParams struct {
	ProxyUserID string `json:"proxy_user_id"`
	ProfileID   string `json:"profile_id"`
}

func (q *Queries) AssignMihomoProfileToUser(ctx context.Context, arg AssignMihomoProfileToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignMihomoProfileToUser, arg.ProxyUserID, arg.ProfileID)
	return err
}

const createMihomoProfile = `-- name: CreateMihomoProfile :exec
INSERT INTO mihomo_profiles (
  id,
  name,
  description,
  draft_document_json,
  proxy_user_id
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
`

type CreateMihomoProfileParams struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	DraftDocumentJson string         `json:"draft_document_json"`
	ProxyUserID       sql.NullString `json:"proxy_user_id"`
}

func (q *Queries) CreateMihomoProfile(ctx context.Context, arg CreateMihomoProfileParams) error {
	_, err := q.db.ExecContext(ctx, createMihomoProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DraftDocumentJson,
		arg.ProxyUserID,
	)
	return err
}

const createMihomoRewriteTemplate = `-- name: CreateMihomoRewriteTemplate :exec
INSERT INTO mihomo_rewrite_templates (
  id, name, description, kind, content, built_in
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, 0
)
`

type CreateMihomoRewriteTemplateParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
	Content     string `json:"content"`
}

func (q *Queries) CreateMihomoRewriteTemplate(ctx context.Context, arg CreateMihomoRewriteTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createMihomoRewriteTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Content,
	)
	return err
}

const getMihomoProfile = `-- name: GetMihomoProfile :one
SELECT
  p.id,
  p.name,
  p.description,
  COALESCE(p.proxy_user_id, '') AS proxy_user_id,
  COALESCE(u.name, '') AS proxy_user_name,
  p.draft_document_json AS document_json,
  p.created_at,
  p.updated_at
FROM mihomo_profiles p
LEFT JOIN proxy_users u ON u.id = p.proxy_user_id
WHERE p.id = ?1
`

type GetMihomoProfileRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	ProxyUserID   string `json:"proxy_user_id"`
	ProxyUserName string `json:"proxy_user_name"`
	DocumentJson  string `json:"document_json"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) GetMihomoProfile(ctx context.Context, id string) (GetMihomoProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getMihomoProfile, id)
	var i GetMihomoProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.DocumentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMihomoProfileIDForUser = `-- name: GetMihomoProfileIDForUser :one
SELECT COALESCE(binding.profile_id, 'mhp_default') AS profile_id
FROM proxy_users u
LEFT JOIN proxy_user_mihomo_profiles binding ON binding.proxy_user_id = u.id
WHERE u.name = ?1
  AND u.deleted_at IS NULL
`

func (q *Queries) GetMihomoProfileIDForUser(ctx context.Context, proxyUserName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMihomoProfileIDForUser, proxyUserName)
	var profile_id string
	err := row.Scan(&profile_id)
	return profile_id, err
}

const getMihomoRewriteTemplate = `-- name: GetMihomoRewriteTemplate :one
SELECT id, name, description, kind, content, built_in, created_at, updated_at
FROM mihomo_rewrite_templates
WHERE id = ?1
`

func (q *Queries) GetMihomoRewriteTemplate(ctx context.Context, id string) (MihomoRewriteTemplate, error) {
	row := q.db.QueryRowContext(ctx, getMihomoRewriteTemplate, id)
	var i MihomoRewriteTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Content,
		&i.BuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMihomoProfiles = `-- name: ListMihomoProfiles :many
SELECT
  p.id,
  p.name,
  p.description,
  COALESCE(p.proxy_user_id, '') AS proxy_user_id,
  COALESCE(u.name, '') AS proxy_user_name,
  p.draft_document_json AS document_json,
  p.created_at,
  p.updated_at
FROM mihomo_profiles p
LEFT JOIN proxy_users u ON u.id = p.proxy_user_id
WHERE p.proxy_user_id IS NOT NULL
ORDER BY p.updated_at DESC, p.name, p.id
`

type ListMihomoProfilesRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	ProxyUserID   string `json:"proxy_user_id"`
	ProxyUserName string `json:"proxy_user_name"`
	DocumentJson  string `json:"document_json"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) ListMihomoProfiles(ctx context.Context) ([]ListMihomoProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMihomoProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMihomoProfilesRow
	for rows.Next() {
		var i ListMihomoProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProxyUserID,
			&i.ProxyUserName,
			&i.DocumentJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMihomoRewriteTemplates = `-- name: ListMihomoRewriteTemplates :many
SELECT id, name, description, kind, content, built_in, created_at, updated_at
FROM mihomo_rewrite_templates
ORDER BY built_in DESC, name, id
`

func (q *Queries) ListMihomoRewriteTemplates(ctx context.Context) ([]MihomoRewriteTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listMihomoRewriteTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MihomoRewriteTemplate
	for rows.Next() {
		var i MihomoRewriteTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Content,
			&i.BuiltIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMihomoProfileDocument = `-- name: UpdateMihomoProfileDocument :execrows
UPDATE mihomo_profiles
SET
  draft_document_json = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
`

type UpdateMihomoProfileDocumentParams struct {
	DocumentJson string `json:"document_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateMihomoProfileDocument(ctx context.Context, arg UpdateMihomoProfileDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMihomoProfileDocument, arg.DocumentJson, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMihomoRewriteTemplate = `-- name: UpdateMihomoRewriteTemplate :execrows
UPDATE mihomo_rewrite_templates
SET name = ?1,
    description = ?2,
    kind = ?3,
    content = ?4,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?5
  AND built_in = 0
`

type UpdateMihomoRewriteTemplateParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
	Content     string `json:"content"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateMihomoRewriteTemplate(ctx context.Context, arg UpdateMihomoRewriteTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMihomoRewriteTemplate,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Content,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
