// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AuditEvent struct {
	ID           string `json:"id"`
	Actor        string `json:"actor"`
	Action       string `json:"action"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	BeforeJson   string `json:"before_json"`
	AfterJson    string `json:"after_json"`
	CreatedAt    string `json:"created_at"`
}

type ConfigVersion struct {
	ID          string         `json:"id"`
	NodeID      string         `json:"node_id"`
	Version     int64          `json:"version"`
	Status      string         `json:"status"`
	ConfigJson  string         `json:"config_json"`
	ConfigHash  string         `json:"config_hash"`
	CreatedAt   string         `json:"created_at"`
	PublishedAt sql.NullString `json:"published_at"`
}

type LogEvent struct {
	ID           string         `json:"id"`
	NodeID       string         `json:"node_id"`
	ProxyUserID  sql.NullString `json:"proxy_user_id"`
	AuthName     string         `json:"auth_name"`
	SourceIp     string         `json:"source_ip"`
	TargetHost   string         `json:"target_host"`
	TargetPort   int64          `json:"target_port"`
	Action       string         `json:"action"`
	RawMessage   string         `json:"raw_message"`
	Count        int64          `json:"count"`
	AggregateKey string         `json:"aggregate_key"`
	WindowStart  string         `json:"window_start"`
	WindowEnd    string         `json:"window_end"`
	CreatedAt    string         `json:"created_at"`
}

type Node struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	PublicHost     string         `json:"public_host"`
	HostsJson      string         `json:"hosts_json"`
	ApiBaseUrl     string         `json:"api_base_url"`
	Status         string         `json:"status"`
	SingBoxVersion string         `json:"sing_box_version"`
	LastSeenAt     sql.NullString `json:"last_seen_at"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type NodeConfigStatus struct {
	NodeID                 string         `json:"node_id"`
	TargetConfigVersionID  sql.NullString `json:"target_config_version_id"`
	CurrentConfigVersionID sql.NullString `json:"current_config_version_id"`
	LastApplyStatus        string         `json:"last_apply_status"`
	LastApplyError         string         `json:"last_apply_error"`
	UpdatedAt              string         `json:"updated_at"`
}

type NodeHeartbeat struct {
	ID             string `json:"id"`
	NodeID         string `json:"node_id"`
	AgentVersion   string `json:"agent_version"`
	SingBoxVersion string `json:"sing_box_version"`
	Status         string `json:"status"`
	MemoryBytes    int64  `json:"memory_bytes"`
	RxBytes        int64  `json:"rx_bytes"`
	TxBytes        int64  `json:"tx_bytes"`
	PayloadJson    string `json:"payload_json"`
	ReportedAt     string `json:"reported_at"`
	CreatedAt      string `json:"created_at"`
}

type NodeNameAlias struct {
	Alias     string `json:"alias"`
	NodeID    string `json:"node_id"`
	CreatedAt string `json:"created_at"`
}

type NodeOutbound struct {
	ID           string `json:"id"`
	NodeID       string `json:"node_id"`
	Tag          string `json:"tag"`
	Type         string `json:"type"`
	SettingsJson string `json:"settings_json"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type NodeToken struct {
	ID          string         `json:"id"`
	NodeID      string         `json:"node_id"`
	TokenHash   string         `json:"token_hash"`
	TokenDigest sql.NullString `json:"token_digest"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type Proxy struct {
	ID                string  `json:"id"`
	NodeID            string  `json:"node_id"`
	Name              string  `json:"name"`
	Protocol          string  `json:"protocol"`
	Listen            string  `json:"listen"`
	ListenPort        int64   `json:"listen_port"`
	Transport         string  `json:"transport"`
	Enabled           int64   `json:"enabled"`
	TrafficMultiplier float64 `json:"traffic_multiplier"`
	SettingsJson      string  `json:"settings_json"`
	InboundRulesJson  string  `json:"inbound_rules_json"`
	OutboundRulesJson string  `json:"outbound_rules_json"`
	RouteRulesJson    string  `json:"route_rules_json"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
}

type ProxyAccess struct {
	ID                string          `json:"id"`
	ProxyID           string          `json:"proxy_id"`
	ProxyUserID       string          `json:"proxy_user_id"`
	AuthName          string          `json:"auth_name"`
	Enabled           int64           `json:"enabled"`
	QuotaBytes        int64           `json:"quota_bytes"`
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	CredentialJson    string          `json:"credential_json"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type ProxyAccessDetail struct {
	ID                     string          `json:"id"`
	ProxyID                string          `json:"proxy_id"`
	ProxyUserID            string          `json:"proxy_user_id"`
	ProxyUserName          string          `json:"proxy_user_name"`
	NodeID                 string          `json:"node_id"`
	NodeName               string          `json:"node_name"`
	NodePublicHost         string          `json:"node_public_host"`
	ProxyName              string          `json:"proxy_name"`
	Protocol               string          `json:"protocol"`
	Listen                 string          `json:"listen"`
	ListenPort             int64           `json:"listen_port"`
	Transport              string          `json:"transport"`
	ProxyTrafficMultiplier float64         `json:"proxy_traffic_multiplier"`
	ProxyEnabled           int64           `json:"proxy_enabled"`
	SettingsJson           string          `json:"settings_json"`
	AuthName               string          `json:"auth_name"`
	Enabled                int64           `json:"enabled"`
	QuotaBytes             int64           `json:"quota_bytes"`
	TrafficMultiplier      sql.NullFloat64 `json:"traffic_multiplier"`
	CredentialJson         string          `json:"credential_json"`
	ProxyUserStatus        string          `json:"proxy_user_status"`
	NodeStatus             string          `json:"node_status"`
	CreatedAt              string          `json:"created_at"`
	UpdatedAt              string          `json:"updated_at"`
}

type ProxyDetail struct {
	ID                string  `json:"id"`
	NodeID            string  `json:"node_id"`
	NodeName          string  `json:"node_name"`
	NodePublicHost    string  `json:"node_public_host"`
	Name              string  `json:"name"`
	Protocol          string  `json:"protocol"`
	Listen            string  `json:"listen"`
	ListenPort        int64   `json:"listen_port"`
	Transport         string  `json:"transport"`
	Enabled           int64   `json:"enabled"`
	TrafficMultiplier float64 `json:"traffic_multiplier"`
	SettingsJson      string  `json:"settings_json"`
	InboundRulesJson  string  `json:"inbound_rules_json"`
	OutboundRulesJson string  `json:"outbound_rules_json"`
	RouteRulesJson    string  `json:"route_rules_json"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
}

type ProxyNameAlias struct {
	Alias     string `json:"alias"`
	ProxyID   string `json:"proxy_id"`
	CreatedAt string `json:"created_at"`
}

type ProxyUser struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	DisplayName      string         `json:"display_name"`
	Status           string         `json:"status"`
	GlobalQuotaBytes int64          `json:"global_quota_bytes"`
	ExpireAt         sql.NullString `json:"expire_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type RawLogEntry struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	JournalCursor sql.NullString `json:"journal_cursor"`
	MessageHash   string         `json:"message_hash"`
	RawMessage    string         `json:"raw_message"`
	ObservedAt    string         `json:"observed_at"`
	IngestedAt    string         `json:"ingested_at"`
}

type RouteProfile struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	NodeID           sql.NullString `json:"node_id"`
	RulesJson        string         `json:"rules_json"`
	FinalOutboundTag string         `json:"final_outbound_tag"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Setting struct {
	Key       string `json:"key"`
	ValueJson string `json:"value_json"`
	UpdatedAt string `json:"updated_at"`
}

type SubscriptionToken struct {
	ID          string         `json:"id"`
	ProxyUserID string         `json:"proxy_user_id"`
	Token       string         `json:"token"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type SystemLog struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	Service       string         `json:"service"`
	JournalCursor sql.NullString `json:"journal_cursor"`
	MessageHash   string         `json:"message_hash"`
	Level         string         `json:"level"`
	RawMessage    string         `json:"raw_message"`
	ObservedAt    string         `json:"observed_at"`
	IngestedAt    string         `json:"ingested_at"`
}

type TrafficReport struct {
	ID          string `json:"id"`
	NodeID      string `json:"node_id"`
	Sequence    int64  `json:"sequence"`
	AgentBootID string `json:"agent_boot_id"`
	ReportedAt  string `json:"reported_at"`
	CreatedAt   string `json:"created_at"`
}

type TrafficUsageDelta struct {
	ID                  string         `json:"id"`
	ReportID            string         `json:"report_id"`
	NodeID              string         `json:"node_id"`
	ProxyUserID         string         `json:"proxy_user_id"`
	ProxyID             sql.NullString `json:"proxy_id"`
	AuthName            string         `json:"auth_name"`
	Direction           string         `json:"direction"`
	RawBytesDelta       int64          `json:"raw_bytes_delta"`
	EffectiveMultiplier float64        `json:"effective_multiplier"`
	BillableBytesDelta  int64          `json:"billable_bytes_delta"`
	CounterValue        int64          `json:"counter_value"`
	CounterEpoch        int64          `json:"counter_epoch"`
	ObservedAt          string         `json:"observed_at"`
	CreatedAt           string         `json:"created_at"`
}

type UserNodeBinding struct {
	ID                string          `json:"id"`
	ProxyUserID       string          `json:"proxy_user_id"`
	NodeID            string          `json:"node_id"`
	Enabled           int64           `json:"enabled"`
	NodeQuotaBytes    int64           `json:"node_quota_bytes"`
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	RouteProfileID    sql.NullString  `json:"route_profile_id"`
	DisabledReason    string          `json:"disabled_reason"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}
