// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
)

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
  id,
  name,
  public_host,
  hosts_json,
  api_base_url,
  status
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  'active'
)
`

type CreateNodeParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PublicHost string `json:"public_host"`
	HostsJson  string `json:"hosts_json"`
	ApiBaseUrl string `json:"api_base_url"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.PublicHost,
		arg.HostsJson,
		arg.ApiBaseUrl,
	)
	return err
}

const createNodeNameAlias = `-- name: CreateNodeNameAlias :exec
INSERT INTO node_name_aliases (alias, node_id)
VALUES (?1, ?2)
`

type CreateNodeNameAliasParams struct {
	Alias  string `json:"alias"`
	NodeID string `json:"node_id"`
}

func (q *Queries) CreateNodeNameAlias(ctx context.Context, arg CreateNodeNameAliasParams) error {
	_, err := q.db.ExecContext(ctx, createNodeNameAlias, arg.Alias, arg.NodeID)
	return err
}

const deleteNodeNameAlias = `-- name: DeleteNodeNameAlias :exec
DELETE FROM node_name_aliases
WHERE alias = ?1 AND node_id = ?2
`

type DeleteNodeNameAliasParams struct {
	Alias  string `json:"alias"`
	NodeID string `json:"node_id"`
}

func (q *Queries) DeleteNodeNameAlias(ctx context.Context, arg DeleteNodeNameAliasParams) error {
	_, err := q.db.ExecContext(ctx, deleteNodeNameAlias, arg.Alias, arg.NodeID)
	return err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT
  id,
  name,
  public_host,
  hosts_json,
  api_base_url,
  status,
  sing_box_version,
  last_seen_at,
  created_at,
  updated_at
FROM nodes
WHERE name = ?1
   OR id = (
     SELECT node_id
     FROM node_name_aliases
     WHERE alias = ?1
   )
`

func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicHost,
		&i.HostsJson,
		&i.ApiBaseUrl,
		&i.Status,
		&i.SingBoxVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeIDByNameOrAlias = `-- name: GetNodeIDByNameOrAlias :one
SELECT id
FROM nodes
WHERE name = ?1
   OR id = (
     SELECT node_id
     FROM node_name_aliases
     WHERE alias = ?1
   )
`

func (q *Queries) GetNodeIDByNameOrAlias(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getNodeIDByNameOrAlias, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listNodes = `-- name: ListNodes :many
SELECT
  id,
  name,
  public_host,
  hosts_json,
  api_base_url,
  status,
  sing_box_version,
  last_seen_at,
  created_at,
  updated_at
FROM nodes
ORDER BY name
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicHost,
			&i.HostsJson,
			&i.ApiBaseUrl,
			&i.Status,
			&i.SingBoxVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promotePendingNodeToActive = `-- name: PromotePendingNodeToActive :execrows
UPDATE nodes
SET
  status = 'active',
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?1
  AND status = 'pending'
`

func (q *Queries) PromotePendingNodeToActive(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, promotePendingNodeToActive, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameNodeByID = `-- name: RenameNodeByID :execrows
UPDATE nodes
SET
  name = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
`

type RenameNodeByIDParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) RenameNodeByID(ctx context.Context, arg RenameNodeByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameNodeByID, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNodeStatus = `-- name: SetNodeStatus :execrows
UPDATE nodes
SET
  status = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?2
`

type SetNodeStatusParams struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNodeStatus, arg.Status, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNode = `-- name: UpdateNode :execrows
UPDATE nodes
SET
  public_host = ?1,
  hosts_json = ?2,
  api_base_url = ?3,
  status = ?4,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?5
`

type UpdateNodeParams struct {
	PublicHost string `json:"public_host"`
	HostsJson  string `json:"hosts_json"`
	ApiBaseUrl string `json:"api_base_url"`
	Status     string `json:"status"`
	Name       string `json:"name"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNode,
		arg.PublicHost,
		arg.HostsJson,
		arg.ApiBaseUrl,
		arg.Status,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
