// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
)

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
  id,
  name,
  public_host,
  api_base_url,
  status
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  'active'
)
`

type CreateNodeParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PublicHost string `json:"public_host"`
	ApiBaseUrl string `json:"api_base_url"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.PublicHost,
		arg.ApiBaseUrl,
	)
	return err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT
  id,
  name,
  public_host,
  api_base_url,
  status,
  sing_box_version,
  last_seen_at,
  created_at,
  updated_at
FROM nodes
WHERE name = ?1
`

func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicHost,
		&i.ApiBaseUrl,
		&i.Status,
		&i.SingBoxVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT
  id,
  name,
  public_host,
  api_base_url,
  status,
  sing_box_version,
  last_seen_at,
  created_at,
  updated_at
FROM nodes
ORDER BY name
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicHost,
			&i.ApiBaseUrl,
			&i.Status,
			&i.SingBoxVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeStatus = `-- name: SetNodeStatus :execrows
UPDATE nodes
SET
  status = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?2
`

type SetNodeStatusParams struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNodeStatus, arg.Status, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNode = `-- name: UpdateNode :execrows
UPDATE nodes
SET
  public_host = ?1,
  api_base_url = ?2,
  status = ?3,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?4
`

type UpdateNodeParams struct {
	PublicHost string `json:"public_host"`
	ApiBaseUrl string `json:"api_base_url"`
	Status     string `json:"status"`
	Name       string `json:"name"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNode,
		arg.PublicHost,
		arg.ApiBaseUrl,
		arg.Status,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
