// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_update_campaigns.sql

package sqlc

import (
	"context"
	"database/sql"
)

const attachNodeUpdateCampaignOperation = `-- name: AttachNodeUpdateCampaignOperation :exec
UPDATE node_update_campaign_members
SET
  operation_id = ?1,
  status = ?2,
  started_at = COALESCE(started_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE campaign_id = ?3
  AND node_id = ?4
  AND operation_id IS NULL
`

type AttachNodeUpdateCampaignOperationParams struct {
	OperationID sql.NullString `json:"operation_id"`
	Status      string         `json:"status"`
	CampaignID  string         `json:"campaign_id"`
	NodeID      string         `json:"node_id"`
}

func (q *Queries) AttachNodeUpdateCampaignOperation(ctx context.Context, arg AttachNodeUpdateCampaignOperationParams) error {
	_, err := q.db.ExecContext(ctx, attachNodeUpdateCampaignOperation,
		arg.OperationID,
		arg.Status,
		arg.CampaignID,
		arg.NodeID,
	)
	return err
}

const createNodeUpdateCampaign = `-- name: CreateNodeUpdateCampaign :exec
INSERT INTO node_update_campaigns (
  id, release, components_json, idempotency_key, spec_hash, batch_size, requested_by
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6, ?7
)
`

type CreateNodeUpdateCampaignParams struct {
	ID             string `json:"id"`
	Release        string `json:"release"`
	ComponentsJson string `json:"components_json"`
	IdempotencyKey string `json:"idempotency_key"`
	SpecHash       string `json:"spec_hash"`
	BatchSize      int64  `json:"batch_size"`
	RequestedBy    string `json:"requested_by"`
}

func (q *Queries) CreateNodeUpdateCampaign(ctx context.Context, arg CreateNodeUpdateCampaignParams) error {
	_, err := q.db.ExecContext(ctx, createNodeUpdateCampaign,
		arg.ID,
		arg.Release,
		arg.ComponentsJson,
		arg.IdempotencyKey,
		arg.SpecHash,
		arg.BatchSize,
		arg.RequestedBy,
	)
	return err
}

const createNodeUpdateCampaignMember = `-- name: CreateNodeUpdateCampaignMember :exec
INSERT INTO node_update_campaign_members (
  campaign_id, node_id, position, batch_number, kind, payload_json
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6
)
`

type CreateNodeUpdateCampaignMemberParams struct {
	CampaignID  string `json:"campaign_id"`
	NodeID      string `json:"node_id"`
	Position    int64  `json:"position"`
	BatchNumber int64  `json:"batch_number"`
	Kind        string `json:"kind"`
	PayloadJson string `json:"payload_json"`
}

func (q *Queries) CreateNodeUpdateCampaignMember(ctx context.Context, arg CreateNodeUpdateCampaignMemberParams) error {
	_, err := q.db.ExecContext(ctx, createNodeUpdateCampaignMember,
		arg.CampaignID,
		arg.NodeID,
		arg.Position,
		arg.BatchNumber,
		arg.Kind,
		arg.PayloadJson,
	)
	return err
}

const getActiveNodeUpdateCampaign = `-- name: GetActiveNodeUpdateCampaign :one
SELECT id, "release", components_json, status, idempotency_key, spec_hash, batch_size, current_batch, requested_by, requested_at, started_at, finished_at, updated_at, error FROM node_update_campaigns
WHERE status IN ('queued', 'running', 'paused')
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetActiveNodeUpdateCampaign(ctx context.Context) (NodeUpdateCampaign, error) {
	row := q.db.QueryRowContext(ctx, getActiveNodeUpdateCampaign)
	var i NodeUpdateCampaign
	err := row.Scan(
		&i.ID,
		&i.Release,
		&i.ComponentsJson,
		&i.Status,
		&i.IdempotencyKey,
		&i.SpecHash,
		&i.BatchSize,
		&i.CurrentBatch,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
	)
	return i, err
}

const getNodeUpdateCampaign = `-- name: GetNodeUpdateCampaign :one
SELECT id, "release", components_json, status, idempotency_key, spec_hash, batch_size, current_batch, requested_by, requested_at, started_at, finished_at, updated_at, error FROM node_update_campaigns WHERE id = ?1
`

func (q *Queries) GetNodeUpdateCampaign(ctx context.Context, id string) (NodeUpdateCampaign, error) {
	row := q.db.QueryRowContext(ctx, getNodeUpdateCampaign, id)
	var i NodeUpdateCampaign
	err := row.Scan(
		&i.ID,
		&i.Release,
		&i.ComponentsJson,
		&i.Status,
		&i.IdempotencyKey,
		&i.SpecHash,
		&i.BatchSize,
		&i.CurrentBatch,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
	)
	return i, err
}

const getNodeUpdateCampaignByIdempotencyKey = `-- name: GetNodeUpdateCampaignByIdempotencyKey :one
SELECT id, "release", components_json, status, idempotency_key, spec_hash, batch_size, current_batch, requested_by, requested_at, started_at, finished_at, updated_at, error FROM node_update_campaigns WHERE idempotency_key = ?1
`

func (q *Queries) GetNodeUpdateCampaignByIdempotencyKey(ctx context.Context, idempotencyKey string) (NodeUpdateCampaign, error) {
	row := q.db.QueryRowContext(ctx, getNodeUpdateCampaignByIdempotencyKey, idempotencyKey)
	var i NodeUpdateCampaign
	err := row.Scan(
		&i.ID,
		&i.Release,
		&i.ComponentsJson,
		&i.Status,
		&i.IdempotencyKey,
		&i.SpecHash,
		&i.BatchSize,
		&i.CurrentBatch,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
	)
	return i, err
}

const getNodeUpdateCampaignIDByOperation = `-- name: GetNodeUpdateCampaignIDByOperation :one
SELECT campaign_id
FROM node_update_campaign_members
WHERE operation_id = ?1
`

func (q *Queries) GetNodeUpdateCampaignIDByOperation(ctx context.Context, operationID sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getNodeUpdateCampaignIDByOperation, operationID)
	var campaign_id string
	err := row.Scan(&campaign_id)
	return campaign_id, err
}

const listNodeUpdateCampaignMembers = `-- name: ListNodeUpdateCampaignMembers :many
SELECT
  m.campaign_id,
  m.node_id,
  n.name AS node_name,
  m.position,
  m.batch_number,
  m.kind,
  m.payload_json,
  m.operation_id,
  m.status,
  m.error,
  m.started_at,
  m.finished_at,
  m.updated_at
FROM node_update_campaign_members m
JOIN nodes n ON n.id = m.node_id
WHERE m.campaign_id = ?1
ORDER BY m.position
`

type ListNodeUpdateCampaignMembersRow struct {
	CampaignID  string         `json:"campaign_id"`
	NodeID      string         `json:"node_id"`
	NodeName    string         `json:"node_name"`
	Position    int64          `json:"position"`
	BatchNumber int64          `json:"batch_number"`
	Kind        string         `json:"kind"`
	PayloadJson string         `json:"payload_json"`
	OperationID sql.NullString `json:"operation_id"`
	Status      string         `json:"status"`
	Error       string         `json:"error"`
	StartedAt   sql.NullString `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) ListNodeUpdateCampaignMembers(ctx context.Context, campaignID string) ([]ListNodeUpdateCampaignMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeUpdateCampaignMembers, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeUpdateCampaignMembersRow
	for rows.Next() {
		var i ListNodeUpdateCampaignMembersRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.NodeID,
			&i.NodeName,
			&i.Position,
			&i.BatchNumber,
			&i.Kind,
			&i.PayloadJson,
			&i.OperationID,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeUpdateCampaigns = `-- name: ListNodeUpdateCampaigns :many
SELECT id, "release", components_json, status, idempotency_key, spec_hash, batch_size, current_batch, requested_by, requested_at, started_at, finished_at, updated_at, error FROM node_update_campaigns
ORDER BY requested_at DESC
LIMIT ?2 OFFSET ?1
`

type ListNodeUpdateCampaignsParams struct {
	ResultOffset int64 `json:"result_offset"`
	ResultLimit  int64 `json:"result_limit"`
}

func (q *Queries) ListNodeUpdateCampaigns(ctx context.Context, arg ListNodeUpdateCampaignsParams) ([]NodeUpdateCampaign, error) {
	rows, err := q.db.QueryContext(ctx, listNodeUpdateCampaigns, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeUpdateCampaign
	for rows.Next() {
		var i NodeUpdateCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Release,
			&i.ComponentsJson,
			&i.Status,
			&i.IdempotencyKey,
			&i.SpecHash,
			&i.BatchSize,
			&i.CurrentBatch,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceNodeUpdateCampaignOperationForRetry = `-- name: ReplaceNodeUpdateCampaignOperationForRetry :exec
UPDATE node_update_campaign_members
SET
  operation_id = ?1,
  status = ?2,
  error = '',
  started_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  finished_at = NULL,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE campaign_id = ?3
  AND node_id = ?4
  AND status IN ('failed', 'cancelled')
`

type ReplaceNodeUpdateCampaignOperationForRetryParams struct {
	OperationID sql.NullString `json:"operation_id"`
	Status      string         `json:"status"`
	CampaignID  string         `json:"campaign_id"`
	NodeID      string         `json:"node_id"`
}

func (q *Queries) ReplaceNodeUpdateCampaignOperationForRetry(ctx context.Context, arg ReplaceNodeUpdateCampaignOperationForRetryParams) error {
	_, err := q.db.ExecContext(ctx, replaceNodeUpdateCampaignOperationForRetry,
		arg.OperationID,
		arg.Status,
		arg.CampaignID,
		arg.NodeID,
	)
	return err
}

const updateNodeUpdateCampaignMemberState = `-- name: UpdateNodeUpdateCampaignMemberState :exec
UPDATE node_update_campaign_members
SET
  status = ?1,
  error = ?2,
  finished_at = COALESCE(?3, finished_at),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE campaign_id = ?4
  AND node_id = ?5
`

type UpdateNodeUpdateCampaignMemberStateParams struct {
	Status         string         `json:"status"`
	Error          string         `json:"error"`
	NextFinishedAt sql.NullString `json:"next_finished_at"`
	CampaignID     string         `json:"campaign_id"`
	NodeID         string         `json:"node_id"`
}

func (q *Queries) UpdateNodeUpdateCampaignMemberState(ctx context.Context, arg UpdateNodeUpdateCampaignMemberStateParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeUpdateCampaignMemberState,
		arg.Status,
		arg.Error,
		arg.NextFinishedAt,
		arg.CampaignID,
		arg.NodeID,
	)
	return err
}

const updateNodeUpdateCampaignState = `-- name: UpdateNodeUpdateCampaignState :exec
UPDATE node_update_campaigns
SET
  status = ?1,
  current_batch = ?2,
  error = ?3,
  started_at = COALESCE(?4, started_at),
  finished_at = COALESCE(?5, finished_at),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?6
`

type UpdateNodeUpdateCampaignStateParams struct {
	Status         string         `json:"status"`
	CurrentBatch   int64          `json:"current_batch"`
	Error          string         `json:"error"`
	NextStartedAt  sql.NullString `json:"next_started_at"`
	NextFinishedAt sql.NullString `json:"next_finished_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateNodeUpdateCampaignState(ctx context.Context, arg UpdateNodeUpdateCampaignStateParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeUpdateCampaignState,
		arg.Status,
		arg.CurrentBatch,
		arg.Error,
		arg.NextStartedAt,
		arg.NextFinishedAt,
		arg.ID,
	)
	return err
}
