// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_tokens.sql

package sqlc

import (
	"context"
)

const createNodeToken = `-- name: CreateNodeToken :exec
INSERT INTO node_tokens (
  id,
  node_id,
  token_hash
) VALUES (
  ?1,
  ?2,
  ?3
)
`

type CreateNodeTokenParams struct {
	ID        string `json:"id"`
	NodeID    string `json:"node_id"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) CreateNodeToken(ctx context.Context, arg CreateNodeTokenParams) error {
	_, err := q.db.ExecContext(ctx, createNodeToken, arg.ID, arg.NodeID, arg.TokenHash)
	return err
}

const listActiveNodeTokensByNodeName = `-- name: ListActiveNodeTokensByNodeName :many
SELECT
  t.id,
  t.node_id,
  t.token_hash,
  t.created_at,
  t.last_used_at,
  t.revoked_at
FROM node_tokens t
JOIN nodes n ON n.id = t.node_id
WHERE n.name = ?1
  AND n.status != 'disabled'
  AND t.revoked_at IS NULL
ORDER BY t.created_at DESC
`

func (q *Queries) ListActiveNodeTokensByNodeName(ctx context.Context, nodeName string) ([]NodeToken, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNodeTokensByNodeName, nodeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeToken
	for rows.Next() {
		var i NodeToken
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeTokenUsed = `-- name: MarkNodeTokenUsed :exec
UPDATE node_tokens
SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
`

func (q *Queries) MarkNodeTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markNodeTokenUsed, id)
	return err
}

const revokeNodeTokensByNodeID = `-- name: RevokeNodeTokensByNodeID :exec
UPDATE node_tokens
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeNodeTokensByNodeID(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, revokeNodeTokensByNodeID, nodeID)
	return err
}
