// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createNodeToken = `-- name: CreateNodeToken :exec
INSERT INTO node_tokens (
  id,
  node_id,
  token_hash,
  token_digest
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
`

type CreateNodeTokenParams struct {
	ID          string         `json:"id"`
	NodeID      string         `json:"node_id"`
	TokenHash   string         `json:"token_hash"`
	TokenDigest sql.NullString `json:"token_digest"`
}

func (q *Queries) CreateNodeToken(ctx context.Context, arg CreateNodeTokenParams) error {
	_, err := q.db.ExecContext(ctx, createNodeToken,
		arg.ID,
		arg.NodeID,
		arg.TokenHash,
		arg.TokenDigest,
	)
	return err
}

const getActiveNodeTokenByDigest = `-- name: GetActiveNodeTokenByDigest :one
SELECT
  t.id,
  t.node_id,
  n.name AS node_name,
  t.token_hash,
  t.token_digest,
  t.created_at,
  t.last_used_at,
  t.revoked_at
FROM node_tokens t
JOIN nodes n ON n.id = t.node_id
WHERE (
    n.name = ?1
    OR n.id = (
      SELECT node_id
      FROM node_name_aliases
      WHERE alias = ?1
    )
  )
  AND t.revoked_at IS NULL
  AND t.token_digest = ?2
`

type GetActiveNodeTokenByDigestParams struct {
	NodeName    string         `json:"node_name"`
	TokenDigest sql.NullString `json:"token_digest"`
}

type GetActiveNodeTokenByDigestRow struct {
	ID          string         `json:"id"`
	NodeID      string         `json:"node_id"`
	NodeName    string         `json:"node_name"`
	TokenHash   string         `json:"token_hash"`
	TokenDigest sql.NullString `json:"token_digest"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

func (q *Queries) GetActiveNodeTokenByDigest(ctx context.Context, arg GetActiveNodeTokenByDigestParams) (GetActiveNodeTokenByDigestRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveNodeTokenByDigest, arg.NodeName, arg.TokenDigest)
	var i GetActiveNodeTokenByDigestRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NodeName,
		&i.TokenHash,
		&i.TokenDigest,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveNodeTokensByNodeName = `-- name: ListActiveNodeTokensByNodeName :many
SELECT
  t.id,
  t.node_id,
  n.name AS node_name,
  t.token_hash,
  t.token_digest,
  t.created_at,
  t.last_used_at,
  t.revoked_at
FROM node_tokens t
JOIN nodes n ON n.id = t.node_id
WHERE (
    n.name = ?1
    OR n.id = (
      SELECT node_id
      FROM node_name_aliases
      WHERE alias = ?1
    )
  )
  AND t.revoked_at IS NULL
ORDER BY t.created_at DESC
`

type ListActiveNodeTokensByNodeNameRow struct {
	ID          string         `json:"id"`
	NodeID      string         `json:"node_id"`
	NodeName    string         `json:"node_name"`
	TokenHash   string         `json:"token_hash"`
	TokenDigest sql.NullString `json:"token_digest"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

func (q *Queries) ListActiveNodeTokensByNodeName(ctx context.Context, nodeName string) ([]ListActiveNodeTokensByNodeNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNodeTokensByNodeName, nodeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNodeTokensByNodeNameRow
	for rows.Next() {
		var i ListActiveNodeTokensByNodeNameRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.NodeName,
			&i.TokenHash,
			&i.TokenDigest,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeNamesWithActiveTokens = `-- name: ListNodeNamesWithActiveTokens :many
SELECT DISTINCT n.name
FROM nodes n
JOIN node_tokens t ON t.node_id = n.id
WHERE t.revoked_at IS NULL
`

func (q *Queries) ListNodeNamesWithActiveTokens(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNodeNamesWithActiveTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeTokenUsed = `-- name: MarkNodeTokenUsed :exec
UPDATE node_tokens
SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
`

func (q *Queries) MarkNodeTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markNodeTokenUsed, id)
	return err
}

const revokeNodeTokensByNodeID = `-- name: RevokeNodeTokensByNodeID :exec
UPDATE node_tokens
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeNodeTokensByNodeID(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, revokeNodeTokensByNodeID, nodeID)
	return err
}
