// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_operations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const appendNodeOperationEvent = `-- name: AppendNodeOperationEvent :exec
INSERT INTO node_operation_events (
  id,
  operation_id,
  attempt,
  sequence,
  status,
  phase,
  message,
  details_json,
  result_json,
  error,
  reported_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11
) ON CONFLICT(operation_id, attempt, sequence) DO NOTHING
`

type AppendNodeOperationEventParams struct {
	ID          string `json:"id"`
	OperationID string `json:"operation_id"`
	Attempt     int64  `json:"attempt"`
	Sequence    int64  `json:"sequence"`
	Status      string `json:"status"`
	Phase       string `json:"phase"`
	Message     string `json:"message"`
	DetailsJson string `json:"details_json"`
	ResultJson  string `json:"result_json"`
	Error       string `json:"error"`
	ReportedAt  string `json:"reported_at"`
}

func (q *Queries) AppendNodeOperationEvent(ctx context.Context, arg AppendNodeOperationEventParams) error {
	_, err := q.db.ExecContext(ctx, appendNodeOperationEvent,
		arg.ID,
		arg.OperationID,
		arg.Attempt,
		arg.Sequence,
		arg.Status,
		arg.Phase,
		arg.Message,
		arg.DetailsJson,
		arg.ResultJson,
		arg.Error,
		arg.ReportedAt,
	)
	return err
}

const applyNodeOperationEvent = `-- name: ApplyNodeOperationEvent :one
UPDATE node_operations
SET
  status = ?1,
  phase = ?2,
  result_json = ?3,
  error = ?4,
  lease_expires_at = CASE
    WHEN ?1 = 'running' THEN ?5
    ELSE NULL
  END,
  lease_token_hash = CASE
    WHEN ?1 = 'running' THEN lease_token_hash
    ELSE NULL
  END,
  finished_at = COALESCE(?6, finished_at),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?7
  AND node_id = ?8
  AND status = 'running'
  AND lease_token_hash = ?9
  AND attempt = ?10
  AND lease_expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
`

type ApplyNodeOperationEventParams struct {
	NextStatus     string         `json:"next_status"`
	Phase          string         `json:"phase"`
	ResultJson     string         `json:"result_json"`
	Error          string         `json:"error"`
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	NextFinishedAt sql.NullString `json:"next_finished_at"`
	ID             string         `json:"id"`
	NodeID         string         `json:"node_id"`
	LeaseTokenHash sql.NullString `json:"lease_token_hash"`
	Attempt        int64          `json:"attempt"`
}

func (q *Queries) ApplyNodeOperationEvent(ctx context.Context, arg ApplyNodeOperationEventParams) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, applyNodeOperationEvent,
		arg.NextStatus,
		arg.Phase,
		arg.ResultJson,
		arg.Error,
		arg.LeaseExpiresAt,
		arg.NextFinishedAt,
		arg.ID,
		arg.NodeID,
		arg.LeaseTokenHash,
		arg.Attempt,
	)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}

const claimNodeOperation = `-- name: ClaimNodeOperation :one
UPDATE node_operations
SET
  status = 'running',
  phase = CASE WHEN status = 'queued' THEN 'claimed' ELSE phase END,
  attempt = attempt + 1,
  lease_token_hash = ?1,
  lease_expires_at = ?2,
  claimed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  started_at = COALESCE(started_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?3
  AND node_id = ?4
  AND cancel_requested = 0
  AND (not_before IS NULL OR not_before <= strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  AND (expires_at IS NULL OR expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
  AND (
    status = 'queued'
    OR (
      status = 'running'
      AND lease_expires_at IS NOT NULL
      AND lease_expires_at <= strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    )
  )
RETURNING id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
`

type ClaimNodeOperationParams struct {
	LeaseTokenHash sql.NullString `json:"lease_token_hash"`
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	ID             string         `json:"id"`
	NodeID         string         `json:"node_id"`
}

func (q *Queries) ClaimNodeOperation(ctx context.Context, arg ClaimNodeOperationParams) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, claimNodeOperation,
		arg.LeaseTokenHash,
		arg.LeaseExpiresAt,
		arg.ID,
		arg.NodeID,
	)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}

const countNodeOperations = `-- name: CountNodeOperations :one
SELECT COUNT(*)
FROM node_operations
WHERE node_id = ?1
`

func (q *Queries) CountNodeOperations(ctx context.Context, nodeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodeOperations, nodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNodeOperation = `-- name: CreateNodeOperation :exec
INSERT INTO node_operations (
  id,
  node_id,
  kind,
  payload_json,
  idempotency_key,
  required_capabilities_json,
  not_before,
  expires_at,
  requested_by,
  retry_of
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
`

type CreateNodeOperationParams struct {
	ID                       string         `json:"id"`
	NodeID                   string         `json:"node_id"`
	Kind                     string         `json:"kind"`
	PayloadJson              string         `json:"payload_json"`
	IdempotencyKey           string         `json:"idempotency_key"`
	RequiredCapabilitiesJson string         `json:"required_capabilities_json"`
	NotBefore                sql.NullString `json:"not_before"`
	ExpiresAt                sql.NullString `json:"expires_at"`
	RequestedBy              string         `json:"requested_by"`
	RetryOf                  sql.NullString `json:"retry_of"`
}

func (q *Queries) CreateNodeOperation(ctx context.Context, arg CreateNodeOperationParams) error {
	_, err := q.db.ExecContext(ctx, createNodeOperation,
		arg.ID,
		arg.NodeID,
		arg.Kind,
		arg.PayloadJson,
		arg.IdempotencyKey,
		arg.RequiredCapabilitiesJson,
		arg.NotBefore,
		arg.ExpiresAt,
		arg.RequestedBy,
		arg.RetryOf,
	)
	return err
}

const expireQueuedNodeOperations = `-- name: ExpireQueuedNodeOperations :exec
UPDATE node_operations
SET
  status = 'expired',
  phase = 'expired',
  finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  error = 'operation expired before it was claimed'
WHERE node_id = ?1
  AND status = 'queued'
  AND expires_at IS NOT NULL
  AND expires_at <= strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

func (q *Queries) ExpireQueuedNodeOperations(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, expireQueuedNodeOperations, nodeID)
	return err
}

const getActiveNodeOperation = `-- name: GetActiveNodeOperation :one
SELECT id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
FROM node_operations
WHERE node_id = ?1
  AND status IN ('queued', 'running')
ORDER BY requested_at
LIMIT 1
`

func (q *Queries) GetActiveNodeOperation(ctx context.Context, nodeID string) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, getActiveNodeOperation, nodeID)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}

const getNodeOperationByID = `-- name: GetNodeOperationByID :one
SELECT id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of FROM node_operations WHERE id = ?1
`

func (q *Queries) GetNodeOperationByID(ctx context.Context, id string) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, getNodeOperationByID, id)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}

const getNodeOperationByIdempotencyKey = `-- name: GetNodeOperationByIdempotencyKey :one
SELECT id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
FROM node_operations
WHERE node_id = ?1
  AND idempotency_key = ?2
`

type GetNodeOperationByIdempotencyKeyParams struct {
	NodeID         string `json:"node_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetNodeOperationByIdempotencyKey(ctx context.Context, arg GetNodeOperationByIdempotencyKeyParams) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, getNodeOperationByIdempotencyKey, arg.NodeID, arg.IdempotencyKey)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}

const getNodeOperationEvent = `-- name: GetNodeOperationEvent :one
SELECT id, operation_id, attempt, sequence, status, phase, message, details_json, result_json, error, reported_at, created_at
FROM node_operation_events
WHERE operation_id = ?1
  AND attempt = ?2
  AND sequence = ?3
`

type GetNodeOperationEventParams struct {
	OperationID string `json:"operation_id"`
	Attempt     int64  `json:"attempt"`
	Sequence    int64  `json:"sequence"`
}

func (q *Queries) GetNodeOperationEvent(ctx context.Context, arg GetNodeOperationEventParams) (NodeOperationEvent, error) {
	row := q.db.QueryRowContext(ctx, getNodeOperationEvent, arg.OperationID, arg.Attempt, arg.Sequence)
	var i NodeOperationEvent
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Attempt,
		&i.Sequence,
		&i.Status,
		&i.Phase,
		&i.Message,
		&i.DetailsJson,
		&i.ResultJson,
		&i.Error,
		&i.ReportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lastNodeOperationEventSequence = `-- name: LastNodeOperationEventSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER)
FROM node_operation_events
WHERE operation_id = ?1
  AND attempt = ?2
`

type LastNodeOperationEventSequenceParams struct {
	OperationID string `json:"operation_id"`
	Attempt     int64  `json:"attempt"`
}

func (q *Queries) LastNodeOperationEventSequence(ctx context.Context, arg LastNodeOperationEventSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastNodeOperationEventSequence, arg.OperationID, arg.Attempt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveNodeOperations = `-- name: ListActiveNodeOperations :many
SELECT id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
FROM node_operations
WHERE status IN ('queued', 'running')
ORDER BY requested_at
`

func (q *Queries) ListActiveNodeOperations(ctx context.Context) ([]NodeOperation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNodeOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeOperation
	for rows.Next() {
		var i NodeOperation
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.Status,
			&i.Phase,
			&i.PayloadJson,
			&i.ResultJson,
			&i.IdempotencyKey,
			&i.RequiredCapabilitiesJson,
			&i.Attempt,
			&i.LeaseTokenHash,
			&i.LeaseExpiresAt,
			&i.CancelRequested,
			&i.NotBefore,
			&i.ExpiresAt,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.Error,
			&i.RetryOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeOperationEvents = `-- name: ListNodeOperationEvents :many
SELECT id, operation_id, attempt, sequence, status, phase, message, details_json, result_json, error, reported_at, created_at
FROM node_operation_events
WHERE operation_id = ?1
ORDER BY attempt, sequence
`

func (q *Queries) ListNodeOperationEvents(ctx context.Context, operationID string) ([]NodeOperationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listNodeOperationEvents, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeOperationEvent
	for rows.Next() {
		var i NodeOperationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Attempt,
			&i.Sequence,
			&i.Status,
			&i.Phase,
			&i.Message,
			&i.DetailsJson,
			&i.ResultJson,
			&i.Error,
			&i.ReportedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeOperations = `-- name: ListNodeOperations :many
SELECT id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
FROM node_operations
WHERE node_id = ?1
ORDER BY requested_at DESC
LIMIT ?3
OFFSET ?2
`

type ListNodeOperationsParams struct {
	NodeID       string `json:"node_id"`
	ResultOffset int64  `json:"result_offset"`
	ResultLimit  int64  `json:"result_limit"`
}

func (q *Queries) ListNodeOperations(ctx context.Context, arg ListNodeOperationsParams) ([]NodeOperation, error) {
	rows, err := q.db.QueryContext(ctx, listNodeOperations, arg.NodeID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeOperation
	for rows.Next() {
		var i NodeOperation
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.Status,
			&i.Phase,
			&i.PayloadJson,
			&i.ResultJson,
			&i.IdempotencyKey,
			&i.RequiredCapabilitiesJson,
			&i.Attempt,
			&i.LeaseTokenHash,
			&i.LeaseExpiresAt,
			&i.CancelRequested,
			&i.NotBefore,
			&i.ExpiresAt,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.Error,
			&i.RetryOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewNodeOperationLease = `-- name: RenewNodeOperationLease :one
UPDATE node_operations
SET
  lease_expires_at = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
  AND node_id = ?3
  AND status = 'running'
  AND lease_token_hash = ?4
  AND attempt = ?5
  AND lease_expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING cancel_requested
`

type RenewNodeOperationLeaseParams struct {
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	ID             string         `json:"id"`
	NodeID         string         `json:"node_id"`
	LeaseTokenHash sql.NullString `json:"lease_token_hash"`
	Attempt        int64          `json:"attempt"`
}

func (q *Queries) RenewNodeOperationLease(ctx context.Context, arg RenewNodeOperationLeaseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, renewNodeOperationLease,
		arg.LeaseExpiresAt,
		arg.ID,
		arg.NodeID,
		arg.LeaseTokenHash,
		arg.Attempt,
	)
	var cancel_requested int64
	err := row.Scan(&cancel_requested)
	return cancel_requested, err
}

const requestNodeOperationCancel = `-- name: RequestNodeOperationCancel :one
UPDATE node_operations
SET
  cancel_requested = 1,
  status = CASE WHEN status = 'queued' THEN 'cancelled' ELSE status END,
  phase = CASE WHEN status = 'queued' THEN 'cancelled' ELSE phase END,
  finished_at = CASE
    WHEN status = 'queued' THEN strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    ELSE finished_at
  END,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND status IN ('queued', 'running')
RETURNING id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
`

func (q *Queries) RequestNodeOperationCancel(ctx context.Context, id string) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, requestNodeOperationCancel, id)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}

const resumeNodeOperationLease = `-- name: ResumeNodeOperationLease :one
UPDATE node_operations
SET
  lease_expires_at = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
  AND node_id = ?3
  AND status = 'running'
  AND lease_token_hash = ?4
  AND lease_expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING id, node_id, kind, status, phase, payload_json, result_json, idempotency_key, required_capabilities_json, attempt, lease_token_hash, lease_expires_at, cancel_requested, not_before, expires_at, requested_by, requested_at, claimed_at, started_at, finished_at, updated_at, error, retry_of
`

type ResumeNodeOperationLeaseParams struct {
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	ID             string         `json:"id"`
	NodeID         string         `json:"node_id"`
	LeaseTokenHash sql.NullString `json:"lease_token_hash"`
}

func (q *Queries) ResumeNodeOperationLease(ctx context.Context, arg ResumeNodeOperationLeaseParams) (NodeOperation, error) {
	row := q.db.QueryRowContext(ctx, resumeNodeOperationLease,
		arg.LeaseExpiresAt,
		arg.ID,
		arg.NodeID,
		arg.LeaseTokenHash,
	)
	var i NodeOperation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Status,
		&i.Phase,
		&i.PayloadJson,
		&i.ResultJson,
		&i.IdempotencyKey,
		&i.RequiredCapabilitiesJson,
		&i.Attempt,
		&i.LeaseTokenHash,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Error,
		&i.RetryOf,
	)
	return i, err
}
