// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paths.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPathsByEndpointID = `-- name: CountPathsByEndpointID :one
SELECT COUNT(*) FROM paths WHERE endpoint_id = ?1
`

func (q *Queries) CountPathsByEndpointID(ctx context.Context, endpointID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPathsByEndpointID, endpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPath = `-- name: CreatePath :exec
INSERT INTO paths (
  id, name, display_name, endpoint_id, dialer_path_id,
  enabled, visibility, managed, sort_order
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9
)
`

type CreatePathParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	DisplayName  string         `json:"display_name"`
	EndpointID   string         `json:"endpoint_id"`
	DialerPathID sql.NullString `json:"dialer_path_id"`
	Enabled      int64          `json:"enabled"`
	Visibility   string         `json:"visibility"`
	Managed      int64          `json:"managed"`
	SortOrder    int64          `json:"sort_order"`
}

func (q *Queries) CreatePath(ctx context.Context, arg CreatePathParams) error {
	_, err := q.db.ExecContext(ctx, createPath,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.EndpointID,
		arg.DialerPathID,
		arg.Enabled,
		arg.Visibility,
		arg.Managed,
		arg.SortOrder,
	)
	return err
}

const createPathAccess = `-- name: CreatePathAccess :exec
INSERT INTO path_accesses (id, path_id, proxy_user_id, enabled)
VALUES (?1, ?2, ?3, ?4)
`

type CreatePathAccessParams struct {
	ID          string `json:"id"`
	PathID      string `json:"path_id"`
	ProxyUserID string `json:"proxy_user_id"`
	Enabled     int64  `json:"enabled"`
}

func (q *Queries) CreatePathAccess(ctx context.Context, arg CreatePathAccessParams) error {
	_, err := q.db.ExecContext(ctx, createPathAccess,
		arg.ID,
		arg.PathID,
		arg.ProxyUserID,
		arg.Enabled,
	)
	return err
}

const deletePath = `-- name: DeletePath :execrows
DELETE FROM paths WHERE id = ?1
`

func (q *Queries) DeletePath(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePath, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPathAccessByIDs = `-- name: GetPathAccessByIDs :one
SELECT id, path_id, proxy_user_id, enabled, deleted_at, created_at, updated_at FROM path_accesses
WHERE path_id = ?1 AND proxy_user_id = ?2
`

type GetPathAccessByIDsParams struct {
	PathID      string `json:"path_id"`
	ProxyUserID string `json:"proxy_user_id"`
}

func (q *Queries) GetPathAccessByIDs(ctx context.Context, arg GetPathAccessByIDsParams) (PathAccess, error) {
	row := q.db.QueryRowContext(ctx, getPathAccessByIDs, arg.PathID, arg.ProxyUserID)
	var i PathAccess
	err := row.Scan(
		&i.ID,
		&i.PathID,
		&i.ProxyUserID,
		&i.Enabled,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPathByID = `-- name: GetPathByID :one
SELECT id, name, display_name, endpoint_id, dialer_path_id, enabled, visibility, managed, sort_order, created_at, updated_at FROM paths WHERE id = ?1
`

func (q *Queries) GetPathByID(ctx context.Context, id string) (Path, error) {
	row := q.db.QueryRowContext(ctx, getPathByID, id)
	var i Path
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.EndpointID,
		&i.DialerPathID,
		&i.Enabled,
		&i.Visibility,
		&i.Managed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePathAccessesByUserID = `-- name: ListActivePathAccessesByUserID :many
SELECT id, path_id, proxy_user_id, enabled, deleted_at, created_at, updated_at FROM path_accesses
WHERE proxy_user_id = ?1
  AND enabled = 1
  AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListActivePathAccessesByUserID(ctx context.Context, proxyUserID string) ([]PathAccess, error) {
	rows, err := q.db.QueryContext(ctx, listActivePathAccessesByUserID, proxyUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PathAccess
	for rows.Next() {
		var i PathAccess
		if err := rows.Scan(
			&i.ID,
			&i.PathID,
			&i.ProxyUserID,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaths = `-- name: ListPaths :many
SELECT id, name, display_name, endpoint_id, dialer_path_id, enabled, visibility, managed, sort_order, created_at, updated_at FROM paths ORDER BY sort_order, name, id
`

func (q *Queries) ListPaths(ctx context.Context) ([]Path, error) {
	rows, err := q.db.QueryContext(ctx, listPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Path
	for rows.Next() {
		var i Path
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.EndpointID,
			&i.DialerPathID,
			&i.Enabled,
			&i.Visibility,
			&i.Managed,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathsByEndpointID = `-- name: ListPathsByEndpointID :many
SELECT id, name, display_name, endpoint_id, dialer_path_id, enabled, visibility, managed, sort_order, created_at, updated_at FROM paths
WHERE endpoint_id = ?1
ORDER BY sort_order, name, id
`

func (q *Queries) ListPathsByEndpointID(ctx context.Context, endpointID string) ([]Path, error) {
	rows, err := q.db.QueryContext(ctx, listPathsByEndpointID, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Path
	for rows.Next() {
		var i Path
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.EndpointID,
			&i.DialerPathID,
			&i.Enabled,
			&i.Visibility,
			&i.Managed,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNamesByPathID = `-- name: ListUserNamesByPathID :many
SELECT u.name
FROM path_accesses a
JOIN proxy_users u ON u.id = a.proxy_user_id
WHERE a.path_id = ?1
  AND a.enabled = 1
  AND a.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY u.name
`

func (q *Queries) ListUserNamesByPathID(ctx context.Context, pathID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserNamesByPathID, pathID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNamesWithActivePathAccess = `-- name: ListUserNamesWithActivePathAccess :many
SELECT DISTINCT u.name
FROM path_accesses a
JOIN proxy_users u ON u.id = a.proxy_user_id
WHERE a.enabled = 1
  AND a.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY u.name
`

func (q *Queries) ListUserNamesWithActivePathAccess(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserNamesWithActivePathAccess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePathAccess = `-- name: RestorePathAccess :execrows
UPDATE path_accesses
SET enabled = 1,
    deleted_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE path_id = ?1 AND proxy_user_id = ?2
`

type RestorePathAccessParams struct {
	PathID      string `json:"path_id"`
	ProxyUserID string `json:"proxy_user_id"`
}

func (q *Queries) RestorePathAccess(ctx context.Context, arg RestorePathAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restorePathAccess, arg.PathID, arg.ProxyUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPathEnabled = `-- name: SetPathEnabled :execrows
UPDATE paths
SET enabled = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
`

type SetPathEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) SetPathEnabled(ctx context.Context, arg SetPathEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPathEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeletePathAccess = `-- name: SoftDeletePathAccess :execrows
UPDATE path_accesses
SET enabled = 0,
    deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE path_id = ?1
  AND proxy_user_id = ?2
  AND deleted_at IS NULL
`

type SoftDeletePathAccessParams struct {
	PathID      string `json:"path_id"`
	ProxyUserID string `json:"proxy_user_id"`
}

func (q *Queries) SoftDeletePathAccess(ctx context.Context, arg SoftDeletePathAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeletePathAccess, arg.PathID, arg.ProxyUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePath = `-- name: UpdatePath :execrows
UPDATE paths
SET name = ?1,
    display_name = ?2,
    endpoint_id = ?3,
    dialer_path_id = ?4,
    enabled = ?5,
    visibility = ?6,
    managed = ?7,
    sort_order = ?8,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?9
`

type UpdatePathParams struct {
	Name         string         `json:"name"`
	DisplayName  string         `json:"display_name"`
	EndpointID   string         `json:"endpoint_id"`
	DialerPathID sql.NullString `json:"dialer_path_id"`
	Enabled      int64          `json:"enabled"`
	Visibility   string         `json:"visibility"`
	Managed      int64          `json:"managed"`
	SortOrder    int64          `json:"sort_order"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdatePath(ctx context.Context, arg UpdatePathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePath,
		arg.Name,
		arg.DisplayName,
		arg.EndpointID,
		arg.DialerPathID,
		arg.Enabled,
		arg.Visibility,
		arg.Managed,
		arg.SortOrder,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
