// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxies.sql

package sqlc

import (
	"context"
)

const createProxy = `-- name: CreateProxy :exec
INSERT INTO proxies (
  id,
  node_id,
  name,
  protocol,
  listen,
  listen_port,
  transport,
  enabled,
  traffic_multiplier,
  settings_json,
  inbound_rules_json,
  outbound_rules_json,
  route_rules_json
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13
)
`

type CreateProxyParams struct {
	ID                string  `json:"id"`
	NodeID            string  `json:"node_id"`
	Name              string  `json:"name"`
	Protocol          string  `json:"protocol"`
	Listen            string  `json:"listen"`
	ListenPort        int64   `json:"listen_port"`
	Transport         string  `json:"transport"`
	Enabled           int64   `json:"enabled"`
	TrafficMultiplier float64 `json:"traffic_multiplier"`
	SettingsJson      string  `json:"settings_json"`
	InboundRulesJson  string  `json:"inbound_rules_json"`
	OutboundRulesJson string  `json:"outbound_rules_json"`
	RouteRulesJson    string  `json:"route_rules_json"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) error {
	_, err := q.db.ExecContext(ctx, createProxy,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.Protocol,
		arg.Listen,
		arg.ListenPort,
		arg.Transport,
		arg.Enabled,
		arg.TrafficMultiplier,
		arg.SettingsJson,
		arg.InboundRulesJson,
		arg.OutboundRulesJson,
		arg.RouteRulesJson,
	)
	return err
}

const createProxyNameAlias = `-- name: CreateProxyNameAlias :exec
INSERT INTO proxy_name_aliases (alias, proxy_id)
VALUES (?1, ?2)
`

type CreateProxyNameAliasParams struct {
	Alias   string `json:"alias"`
	ProxyID string `json:"proxy_id"`
}

func (q *Queries) CreateProxyNameAlias(ctx context.Context, arg CreateProxyNameAliasParams) error {
	_, err := q.db.ExecContext(ctx, createProxyNameAlias, arg.Alias, arg.ProxyID)
	return err
}

const deleteProxyNameAlias = `-- name: DeleteProxyNameAlias :exec
DELETE FROM proxy_name_aliases
WHERE alias = ?1 AND proxy_id = ?2
`

type DeleteProxyNameAliasParams struct {
	Alias   string `json:"alias"`
	ProxyID string `json:"proxy_id"`
}

func (q *Queries) DeleteProxyNameAlias(ctx context.Context, arg DeleteProxyNameAliasParams) error {
	_, err := q.db.ExecContext(ctx, deleteProxyNameAlias, arg.Alias, arg.ProxyID)
	return err
}

const getProxyByNodeAndName = `-- name: GetProxyByNodeAndName :one
SELECT id, node_id, node_name, node_public_host, name, protocol, listen, listen_port, transport, enabled, traffic_multiplier, settings_json, inbound_rules_json, outbound_rules_json, route_rules_json, deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_details
WHERE node_id = (
    SELECT n.id
    FROM nodes n
    WHERE n.name = ?1
       OR n.id = (
         SELECT node_id
         FROM node_name_aliases
         WHERE alias = ?1
       )
  )
  AND deleted_at IS NULL
  AND node_deleted_at IS NULL
  AND id = (
    SELECT p.id
    FROM proxies p
    WHERE p.name = ?2
       OR p.id = (
         SELECT proxy_id
         FROM proxy_name_aliases
         WHERE alias = ?2
       )
  )
`

type GetProxyByNodeAndNameParams struct {
	NodeName string `json:"node_name"`
	Name     string `json:"name"`
}

func (q *Queries) GetProxyByNodeAndName(ctx context.Context, arg GetProxyByNodeAndNameParams) (ProxyDetail, error) {
	row := q.db.QueryRowContext(ctx, getProxyByNodeAndName, arg.NodeName, arg.Name)
	var i ProxyDetail
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NodeName,
		&i.NodePublicHost,
		&i.Name,
		&i.Protocol,
		&i.Listen,
		&i.ListenPort,
		&i.Transport,
		&i.Enabled,
		&i.TrafficMultiplier,
		&i.SettingsJson,
		&i.InboundRulesJson,
		&i.OutboundRulesJson,
		&i.RouteRulesJson,
		&i.DeletedAt,
		&i.NodeDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProxyByNodeAndNameIncludingDeleted = `-- name: GetProxyByNodeAndNameIncludingDeleted :one
SELECT id, node_id, node_name, node_public_host, name, protocol, listen, listen_port, transport, enabled, traffic_multiplier, settings_json, inbound_rules_json, outbound_rules_json, route_rules_json, deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_details
WHERE node_id = (
    SELECT n.id
    FROM nodes n
    WHERE n.name = ?1
       OR n.id = (
         SELECT node_id
         FROM node_name_aliases
         WHERE alias = ?1
       )
  )
  AND id = (
    SELECT p.id
    FROM proxies p
    WHERE p.name = ?2
       OR p.id = (
         SELECT proxy_id
         FROM proxy_name_aliases
         WHERE alias = ?2
       )
  )
`

type GetProxyByNodeAndNameIncludingDeletedParams struct {
	NodeName string `json:"node_name"`
	Name     string `json:"name"`
}

func (q *Queries) GetProxyByNodeAndNameIncludingDeleted(ctx context.Context, arg GetProxyByNodeAndNameIncludingDeletedParams) (ProxyDetail, error) {
	row := q.db.QueryRowContext(ctx, getProxyByNodeAndNameIncludingDeleted, arg.NodeName, arg.Name)
	var i ProxyDetail
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NodeName,
		&i.NodePublicHost,
		&i.Name,
		&i.Protocol,
		&i.Listen,
		&i.ListenPort,
		&i.Transport,
		&i.Enabled,
		&i.TrafficMultiplier,
		&i.SettingsJson,
		&i.InboundRulesJson,
		&i.OutboundRulesJson,
		&i.RouteRulesJson,
		&i.DeletedAt,
		&i.NodeDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProxyIDByNameOrAlias = `-- name: GetProxyIDByNameOrAlias :one
SELECT id
FROM proxies
WHERE name = ?1
   OR id = (
     SELECT proxy_id
     FROM proxy_name_aliases
     WHERE alias = ?1
   )
`

func (q *Queries) GetProxyIDByNameOrAlias(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProxyIDByNameOrAlias, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listProxies = `-- name: ListProxies :many
SELECT id, node_id, node_name, node_public_host, name, protocol, listen, listen_port, transport, enabled, traffic_multiplier, settings_json, inbound_rules_json, outbound_rules_json, route_rules_json, deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_details
WHERE deleted_at IS NULL
  AND node_deleted_at IS NULL
ORDER BY node_name, listen_port, name
`

func (q *Queries) ListProxies(ctx context.Context) ([]ProxyDetail, error) {
	rows, err := q.db.QueryContext(ctx, listProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyDetail
	for rows.Next() {
		var i ProxyDetail
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.NodeName,
			&i.NodePublicHost,
			&i.Name,
			&i.Protocol,
			&i.Listen,
			&i.ListenPort,
			&i.Transport,
			&i.Enabled,
			&i.TrafficMultiplier,
			&i.SettingsJson,
			&i.InboundRulesJson,
			&i.OutboundRulesJson,
			&i.RouteRulesJson,
			&i.DeletedAt,
			&i.NodeDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxiesByNodeName = `-- name: ListProxiesByNodeName :many
SELECT id, node_id, node_name, node_public_host, name, protocol, listen, listen_port, transport, enabled, traffic_multiplier, settings_json, inbound_rules_json, outbound_rules_json, route_rules_json, deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_details
WHERE node_name = ?1
  AND deleted_at IS NULL
  AND node_deleted_at IS NULL
ORDER BY node_name, listen_port, name
`

func (q *Queries) ListProxiesByNodeName(ctx context.Context, nodeName string) ([]ProxyDetail, error) {
	rows, err := q.db.QueryContext(ctx, listProxiesByNodeName, nodeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyDetail
	for rows.Next() {
		var i ProxyDetail
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.NodeName,
			&i.NodePublicHost,
			&i.Name,
			&i.Protocol,
			&i.Listen,
			&i.ListenPort,
			&i.Transport,
			&i.Enabled,
			&i.TrafficMultiplier,
			&i.SettingsJson,
			&i.InboundRulesJson,
			&i.OutboundRulesJson,
			&i.RouteRulesJson,
			&i.DeletedAt,
			&i.NodeDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameProxyByID = `-- name: RenameProxyByID :execrows
UPDATE proxies
SET
  name = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
`

type RenameProxyByIDParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) RenameProxyByID(ctx context.Context, arg RenameProxyByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameProxyByID, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreProxy = `-- name: RestoreProxy :execrows
UPDATE proxies
SET
  deleted_at = NULL,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreProxy(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreProxy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProxyEnabled = `-- name: SetProxyEnabled :execrows
UPDATE proxies
SET
  enabled = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?2 AND name = ?3
  AND deleted_at IS NULL
`

type SetProxyEnabledParams struct {
	Enabled int64  `json:"enabled"`
	NodeID  string `json:"node_id"`
	Name    string `json:"name"`
}

func (q *Queries) SetProxyEnabled(ctx context.Context, arg SetProxyEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProxyEnabled, arg.Enabled, arg.NodeID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteProxy = `-- name: SoftDeleteProxy :execrows
UPDATE proxies
SET
  enabled = 0,
  deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProxy(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteProxy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProxy = `-- name: UpdateProxy :execrows
UPDATE proxies
SET
  listen = ?1,
  listen_port = ?2,
  transport = ?3,
  enabled = ?4,
  traffic_multiplier = ?5,
  settings_json = ?6,
  inbound_rules_json = ?7,
  outbound_rules_json = ?8,
  route_rules_json = ?9,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?10 AND name = ?11
  AND deleted_at IS NULL
`

type UpdateProxyParams struct {
	Listen            string  `json:"listen"`
	ListenPort        int64   `json:"listen_port"`
	Transport         string  `json:"transport"`
	Enabled           int64   `json:"enabled"`
	TrafficMultiplier float64 `json:"traffic_multiplier"`
	SettingsJson      string  `json:"settings_json"`
	InboundRulesJson  string  `json:"inbound_rules_json"`
	OutboundRulesJson string  `json:"outbound_rules_json"`
	RouteRulesJson    string  `json:"route_rules_json"`
	NodeID            string  `json:"node_id"`
	Name              string  `json:"name"`
}

func (q *Queries) UpdateProxy(ctx context.Context, arg UpdateProxyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProxy,
		arg.Listen,
		arg.ListenPort,
		arg.Transport,
		arg.Enabled,
		arg.TrafficMultiplier,
		arg.SettingsJson,
		arg.InboundRulesJson,
		arg.OutboundRulesJson,
		arg.RouteRulesJson,
		arg.NodeID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
