// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_accesses.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProxyAccess = `-- name: CreateProxyAccess :exec
INSERT INTO proxy_accesses (
  id,
  proxy_id,
  proxy_user_id,
  auth_name,
  enabled,
  quota_bytes,
  traffic_multiplier,
  credential_json
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
`

type CreateProxyAccessParams struct {
	ID                string          `json:"id"`
	ProxyID           string          `json:"proxy_id"`
	ProxyUserID       string          `json:"proxy_user_id"`
	AuthName          string          `json:"auth_name"`
	Enabled           int64           `json:"enabled"`
	QuotaBytes        int64           `json:"quota_bytes"`
	TrafficMultiplier sql.NullFloat64 `json:"traffic_multiplier"`
	CredentialJson    string          `json:"credential_json"`
}

func (q *Queries) CreateProxyAccess(ctx context.Context, arg CreateProxyAccessParams) error {
	_, err := q.db.ExecContext(ctx, createProxyAccess,
		arg.ID,
		arg.ProxyID,
		arg.ProxyUserID,
		arg.AuthName,
		arg.Enabled,
		arg.QuotaBytes,
		arg.TrafficMultiplier,
		arg.CredentialJson,
	)
	return err
}

const getProxyAccess = `-- name: GetProxyAccess :one
SELECT id, proxy_id, proxy_user_id, proxy_user_name, node_id, node_name, node_public_host, proxy_name, protocol, listen, listen_port, transport, proxy_traffic_multiplier, proxy_enabled, settings_json, auth_name, enabled, quota_bytes, traffic_multiplier, credential_json, proxy_user_status, node_status, deleted_at, proxy_deleted_at, proxy_user_deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_access_details
WHERE proxy_user_name = ?1
  AND node_name = ?2
  AND proxy_name = ?3
  AND deleted_at IS NULL
  AND proxy_deleted_at IS NULL
  AND proxy_user_deleted_at IS NULL
  AND node_deleted_at IS NULL
`

type GetProxyAccessParams struct {
	UserName  string `json:"user_name"`
	NodeName  string `json:"node_name"`
	ProxyName string `json:"proxy_name"`
}

func (q *Queries) GetProxyAccess(ctx context.Context, arg GetProxyAccessParams) (ProxyAccessDetail, error) {
	row := q.db.QueryRowContext(ctx, getProxyAccess, arg.UserName, arg.NodeName, arg.ProxyName)
	var i ProxyAccessDetail
	err := row.Scan(
		&i.ID,
		&i.ProxyID,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.NodeID,
		&i.NodeName,
		&i.NodePublicHost,
		&i.ProxyName,
		&i.Protocol,
		&i.Listen,
		&i.ListenPort,
		&i.Transport,
		&i.ProxyTrafficMultiplier,
		&i.ProxyEnabled,
		&i.SettingsJson,
		&i.AuthName,
		&i.Enabled,
		&i.QuotaBytes,
		&i.TrafficMultiplier,
		&i.CredentialJson,
		&i.ProxyUserStatus,
		&i.NodeStatus,
		&i.DeletedAt,
		&i.ProxyDeletedAt,
		&i.ProxyUserDeletedAt,
		&i.NodeDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProxyAccessByIDs = `-- name: GetProxyAccessByIDs :one
SELECT id, proxy_id, proxy_user_id, proxy_user_name, node_id, node_name, node_public_host, proxy_name, protocol, listen, listen_port, transport, proxy_traffic_multiplier, proxy_enabled, settings_json, auth_name, enabled, quota_bytes, traffic_multiplier, credential_json, proxy_user_status, node_status, deleted_at, proxy_deleted_at, proxy_user_deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_access_details
WHERE proxy_user_id = ?1
  AND proxy_id = ?2
`

type GetProxyAccessByIDsParams struct {
	ProxyUserID string `json:"proxy_user_id"`
	ProxyID     string `json:"proxy_id"`
}

func (q *Queries) GetProxyAccessByIDs(ctx context.Context, arg GetProxyAccessByIDsParams) (ProxyAccessDetail, error) {
	row := q.db.QueryRowContext(ctx, getProxyAccessByIDs, arg.ProxyUserID, arg.ProxyID)
	var i ProxyAccessDetail
	err := row.Scan(
		&i.ID,
		&i.ProxyID,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.NodeID,
		&i.NodeName,
		&i.NodePublicHost,
		&i.ProxyName,
		&i.Protocol,
		&i.Listen,
		&i.ListenPort,
		&i.Transport,
		&i.ProxyTrafficMultiplier,
		&i.ProxyEnabled,
		&i.SettingsJson,
		&i.AuthName,
		&i.Enabled,
		&i.QuotaBytes,
		&i.TrafficMultiplier,
		&i.CredentialJson,
		&i.ProxyUserStatus,
		&i.NodeStatus,
		&i.DeletedAt,
		&i.ProxyDeletedAt,
		&i.ProxyUserDeletedAt,
		&i.NodeDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyAccessesByNodeName = `-- name: ListProxyAccessesByNodeName :many
SELECT d.id, d.proxy_id, d.proxy_user_id, d.proxy_user_name, d.node_id, d.node_name, d.node_public_host, d.proxy_name, d.protocol, d.listen, d.listen_port, d.transport, d.proxy_traffic_multiplier, d.proxy_enabled, d.settings_json, d.auth_name, d.enabled, d.quota_bytes, d.traffic_multiplier, d.credential_json, d.proxy_user_status, d.node_status, d.deleted_at, d.proxy_deleted_at, d.proxy_user_deleted_at, d.node_deleted_at, d.created_at, d.updated_at
FROM proxy_access_details d
JOIN user_node_bindings b ON b.proxy_user_id = d.proxy_user_id AND b.node_id = d.node_id
WHERE d.node_name = ?1
  AND d.enabled = 1
  AND d.proxy_user_status = 'active'
  AND d.node_status = 'active'
  AND d.proxy_enabled = 1
  AND b.enabled = 1
  AND d.deleted_at IS NULL
  AND d.proxy_deleted_at IS NULL
  AND d.proxy_user_deleted_at IS NULL
  AND d.node_deleted_at IS NULL
ORDER BY d.listen_port, d.proxy_name, d.proxy_user_name
`

func (q *Queries) ListProxyAccessesByNodeName(ctx context.Context, nodeName string) ([]ProxyAccessDetail, error) {
	rows, err := q.db.QueryContext(ctx, listProxyAccessesByNodeName, nodeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyAccessDetail
	for rows.Next() {
		var i ProxyAccessDetail
		if err := rows.Scan(
			&i.ID,
			&i.ProxyID,
			&i.ProxyUserID,
			&i.ProxyUserName,
			&i.NodeID,
			&i.NodeName,
			&i.NodePublicHost,
			&i.ProxyName,
			&i.Protocol,
			&i.Listen,
			&i.ListenPort,
			&i.Transport,
			&i.ProxyTrafficMultiplier,
			&i.ProxyEnabled,
			&i.SettingsJson,
			&i.AuthName,
			&i.Enabled,
			&i.QuotaBytes,
			&i.TrafficMultiplier,
			&i.CredentialJson,
			&i.ProxyUserStatus,
			&i.NodeStatus,
			&i.DeletedAt,
			&i.ProxyDeletedAt,
			&i.ProxyUserDeletedAt,
			&i.NodeDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyAccessesByUserName = `-- name: ListProxyAccessesByUserName :many
SELECT id, proxy_id, proxy_user_id, proxy_user_name, node_id, node_name, node_public_host, proxy_name, protocol, listen, listen_port, transport, proxy_traffic_multiplier, proxy_enabled, settings_json, auth_name, enabled, quota_bytes, traffic_multiplier, credential_json, proxy_user_status, node_status, deleted_at, proxy_deleted_at, proxy_user_deleted_at, node_deleted_at, created_at, updated_at
FROM proxy_access_details
WHERE proxy_user_name = ?1
  AND deleted_at IS NULL
  AND proxy_deleted_at IS NULL
  AND proxy_user_deleted_at IS NULL
  AND node_deleted_at IS NULL
ORDER BY node_name, listen_port, proxy_name
`

func (q *Queries) ListProxyAccessesByUserName(ctx context.Context, userName string) ([]ProxyAccessDetail, error) {
	rows, err := q.db.QueryContext(ctx, listProxyAccessesByUserName, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyAccessDetail
	for rows.Next() {
		var i ProxyAccessDetail
		if err := rows.Scan(
			&i.ID,
			&i.ProxyID,
			&i.ProxyUserID,
			&i.ProxyUserName,
			&i.NodeID,
			&i.NodeName,
			&i.NodePublicHost,
			&i.ProxyName,
			&i.Protocol,
			&i.Listen,
			&i.ListenPort,
			&i.Transport,
			&i.ProxyTrafficMultiplier,
			&i.ProxyEnabled,
			&i.SettingsJson,
			&i.AuthName,
			&i.Enabled,
			&i.QuotaBytes,
			&i.TrafficMultiplier,
			&i.CredentialJson,
			&i.ProxyUserStatus,
			&i.NodeStatus,
			&i.DeletedAt,
			&i.ProxyDeletedAt,
			&i.ProxyUserDeletedAt,
			&i.NodeDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyAccessesByUserNode = `-- name: ListProxyAccessesByUserNode :many
SELECT d.id, d.proxy_id, d.proxy_user_id, d.proxy_user_name, d.node_id, d.node_name, d.node_public_host, d.proxy_name, d.protocol, d.listen, d.listen_port, d.transport, d.proxy_traffic_multiplier, d.proxy_enabled, d.settings_json, d.auth_name, d.enabled, d.quota_bytes, d.traffic_multiplier, d.credential_json, d.proxy_user_status, d.node_status, d.deleted_at, d.proxy_deleted_at, d.proxy_user_deleted_at, d.node_deleted_at, d.created_at, d.updated_at
FROM proxy_access_details d
JOIN user_node_bindings b ON b.proxy_user_id = d.proxy_user_id AND b.node_id = d.node_id
WHERE d.proxy_user_name = ?1
  AND d.node_name = ?2
  AND d.enabled = 1
  AND d.proxy_user_status = 'active'
  AND d.node_status = 'active'
  AND d.proxy_enabled = 1
  AND b.enabled = 1
  AND d.deleted_at IS NULL
  AND d.proxy_deleted_at IS NULL
  AND d.proxy_user_deleted_at IS NULL
  AND d.node_deleted_at IS NULL
ORDER BY d.listen_port, d.proxy_name
`

type ListProxyAccessesByUserNodeParams struct {
	UserName string `json:"user_name"`
	NodeName string `json:"node_name"`
}

func (q *Queries) ListProxyAccessesByUserNode(ctx context.Context, arg ListProxyAccessesByUserNodeParams) ([]ProxyAccessDetail, error) {
	rows, err := q.db.QueryContext(ctx, listProxyAccessesByUserNode, arg.UserName, arg.NodeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyAccessDetail
	for rows.Next() {
		var i ProxyAccessDetail
		if err := rows.Scan(
			&i.ID,
			&i.ProxyID,
			&i.ProxyUserID,
			&i.ProxyUserName,
			&i.NodeID,
			&i.NodeName,
			&i.NodePublicHost,
			&i.ProxyName,
			&i.Protocol,
			&i.Listen,
			&i.ListenPort,
			&i.Transport,
			&i.ProxyTrafficMultiplier,
			&i.ProxyEnabled,
			&i.SettingsJson,
			&i.AuthName,
			&i.Enabled,
			&i.QuotaBytes,
			&i.TrafficMultiplier,
			&i.CredentialJson,
			&i.ProxyUserStatus,
			&i.NodeStatus,
			&i.DeletedAt,
			&i.ProxyDeletedAt,
			&i.ProxyUserDeletedAt,
			&i.NodeDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProxyAccess = `-- name: RestoreProxyAccess :execrows
UPDATE proxy_accesses
SET
  enabled = 1,
  deleted_at = NULL,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?1
  AND proxy_id = ?2
`

type RestoreProxyAccessParams struct {
	ProxyUserID string `json:"proxy_user_id"`
	ProxyID     string `json:"proxy_id"`
}

func (q *Queries) RestoreProxyAccess(ctx context.Context, arg RestoreProxyAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreProxyAccess, arg.ProxyUserID, arg.ProxyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProxyAccessEnabled = `-- name: SetProxyAccessEnabled :execrows
UPDATE proxy_accesses
SET
  enabled = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?2
  AND proxy_id = ?3
  AND deleted_at IS NULL
`

type SetProxyAccessEnabledParams struct {
	Enabled     int64  `json:"enabled"`
	ProxyUserID string `json:"proxy_user_id"`
	ProxyID     string `json:"proxy_id"`
}

func (q *Queries) SetProxyAccessEnabled(ctx context.Context, arg SetProxyAccessEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProxyAccessEnabled, arg.Enabled, arg.ProxyUserID, arg.ProxyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteProxyAccess = `-- name: SoftDeleteProxyAccess :execrows
UPDATE proxy_accesses
SET
  enabled = 0,
  deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?1
  AND proxy_id = ?2
  AND deleted_at IS NULL
`

type SoftDeleteProxyAccessParams struct {
	ProxyUserID string `json:"proxy_user_id"`
	ProxyID     string `json:"proxy_id"`
}

func (q *Queries) SoftDeleteProxyAccess(ctx context.Context, arg SoftDeleteProxyAccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteProxyAccess, arg.ProxyUserID, arg.ProxyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
