// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_publication_settings.sql

package sqlc

import (
	"context"
)

const getProxyDirectPublication = `-- name: GetProxyDirectPublication :one
SELECT direct_enabled
FROM proxy_publication_settings
WHERE proxy_id = ?1
`

func (q *Queries) GetProxyDirectPublication(ctx context.Context, proxyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProxyDirectPublication, proxyID)
	var direct_enabled int64
	err := row.Scan(&direct_enabled)
	return direct_enabled, err
}

const setProxyDirectPublication = `-- name: SetProxyDirectPublication :exec
INSERT INTO proxy_publication_settings (proxy_id, direct_enabled)
VALUES (?1, ?2)
ON CONFLICT (proxy_id) DO UPDATE SET
  direct_enabled = excluded.direct_enabled,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type SetProxyDirectPublicationParams struct {
	ProxyID       string `json:"proxy_id"`
	DirectEnabled int64  `json:"direct_enabled"`
}

func (q *Queries) SetProxyDirectPublication(ctx context.Context, arg SetProxyDirectPublicationParams) error {
	_, err := q.db.ExecContext(ctx, setProxyDirectPublication, arg.ProxyID, arg.DirectEnabled)
	return err
}
