// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_log_entries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRawLogEntry = `-- name: CreateRawLogEntry :execrows
INSERT OR IGNORE INTO raw_log_entries (
  id,
  node_id,
  journal_cursor,
  message_hash,
  raw_message,
  observed_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6
)
`

type CreateRawLogEntryParams struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	JournalCursor sql.NullString `json:"journal_cursor"`
	MessageHash   string         `json:"message_hash"`
	RawMessage    string         `json:"raw_message"`
	ObservedAt    string         `json:"observed_at"`
}

func (q *Queries) CreateRawLogEntry(ctx context.Context, arg CreateRawLogEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRawLogEntry,
		arg.ID,
		arg.NodeID,
		arg.JournalCursor,
		arg.MessageHash,
		arg.RawMessage,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listRecentRawLogEntriesByNode = `-- name: ListRecentRawLogEntriesByNode :many
SELECT
  r.id,
  r.node_id,
  r.journal_cursor,
  r.message_hash,
  r.raw_message,
  r.observed_at,
  r.ingested_at
FROM raw_log_entries r
JOIN nodes n ON n.id = r.node_id
WHERE n.name = ?1
ORDER BY r.observed_at DESC
LIMIT ?2
`

type ListRecentRawLogEntriesByNodeParams struct {
	NodeName string `json:"node_name"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListRecentRawLogEntriesByNode(ctx context.Context, arg ListRecentRawLogEntriesByNodeParams) ([]RawLogEntry, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRawLogEntriesByNode, arg.NodeName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawLogEntry
	for rows.Next() {
		var i RawLogEntry
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.JournalCursor,
			&i.MessageHash,
			&i.RawMessage,
			&i.ObservedAt,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
