// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSubscriptionToken = `-- name: CreateSubscriptionToken :exec
INSERT INTO subscription_tokens (
  id,
  proxy_user_id,
  token
) VALUES (
  ?1,
  ?2,
  ?3
)
`

type CreateSubscriptionTokenParams struct {
	ID          string `json:"id"`
	ProxyUserID string `json:"proxy_user_id"`
	Token       string `json:"token"`
}

func (q *Queries) CreateSubscriptionToken(ctx context.Context, arg CreateSubscriptionTokenParams) error {
	_, err := q.db.ExecContext(ctx, createSubscriptionToken, arg.ID, arg.ProxyUserID, arg.Token)
	return err
}

const getActiveSubscriptionTokenByUserName = `-- name: GetActiveSubscriptionTokenByUserName :one
SELECT
  t.id,
  t.proxy_user_id,
  u.name AS proxy_user_name,
  t.token,
  t.created_at,
  t.last_used_at,
  t.revoked_at
FROM subscription_tokens t
JOIN proxy_users u ON u.id = t.proxy_user_id
WHERE u.name = ?1
  AND u.deleted_at IS NULL
  AND t.revoked_at IS NULL
`

type GetActiveSubscriptionTokenByUserNameRow struct {
	ID            string         `json:"id"`
	ProxyUserID   string         `json:"proxy_user_id"`
	ProxyUserName string         `json:"proxy_user_name"`
	Token         string         `json:"token"`
	CreatedAt     string         `json:"created_at"`
	LastUsedAt    sql.NullString `json:"last_used_at"`
	RevokedAt     sql.NullString `json:"revoked_at"`
}

func (q *Queries) GetActiveSubscriptionTokenByUserName(ctx context.Context, proxyUserName string) (GetActiveSubscriptionTokenByUserNameRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionTokenByUserName, proxyUserName)
	var i GetActiveSubscriptionTokenByUserNameRow
	err := row.Scan(
		&i.ID,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.Token,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSubscriptionTokenByValue = `-- name: GetActiveSubscriptionTokenByValue :one
SELECT
  t.id,
  t.proxy_user_id,
  u.name AS proxy_user_name,
  t.token,
  t.created_at,
  t.last_used_at,
  t.revoked_at
FROM subscription_tokens t
JOIN proxy_users u ON u.id = t.proxy_user_id
WHERE t.token = ?1
  AND u.deleted_at IS NULL
  AND t.revoked_at IS NULL
`

type GetActiveSubscriptionTokenByValueRow struct {
	ID            string         `json:"id"`
	ProxyUserID   string         `json:"proxy_user_id"`
	ProxyUserName string         `json:"proxy_user_name"`
	Token         string         `json:"token"`
	CreatedAt     string         `json:"created_at"`
	LastUsedAt    sql.NullString `json:"last_used_at"`
	RevokedAt     sql.NullString `json:"revoked_at"`
}

func (q *Queries) GetActiveSubscriptionTokenByValue(ctx context.Context, token string) (GetActiveSubscriptionTokenByValueRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionTokenByValue, token)
	var i GetActiveSubscriptionTokenByValueRow
	err := row.Scan(
		&i.ID,
		&i.ProxyUserID,
		&i.ProxyUserName,
		&i.Token,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markSubscriptionTokenUsed = `-- name: MarkSubscriptionTokenUsed :exec
UPDATE subscription_tokens
SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) MarkSubscriptionTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markSubscriptionTokenUsed, id)
	return err
}

const revokeActiveSubscriptionTokenByUserID = `-- name: RevokeActiveSubscriptionTokenByUserID :execrows
UPDATE subscription_tokens
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE proxy_user_id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeActiveSubscriptionTokenByUserID(ctx context.Context, proxyUserID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeActiveSubscriptionTokenByUserID, proxyUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
