// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_logs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSystemLog = `-- name: CreateSystemLog :execrows
INSERT OR IGNORE INTO system_logs (
  id,
  node_id,
  service,
  journal_cursor,
  message_hash,
  level,
  raw_message,
  observed_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
`

type CreateSystemLogParams struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	Service       string         `json:"service"`
	JournalCursor sql.NullString `json:"journal_cursor"`
	MessageHash   string         `json:"message_hash"`
	Level         string         `json:"level"`
	RawMessage    string         `json:"raw_message"`
	ObservedAt    string         `json:"observed_at"`
}

func (q *Queries) CreateSystemLog(ctx context.Context, arg CreateSystemLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSystemLog,
		arg.ID,
		arg.NodeID,
		arg.Service,
		arg.JournalCursor,
		arg.MessageHash,
		arg.Level,
		arg.RawMessage,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listRecentSystemLogs = `-- name: ListRecentSystemLogs :many
SELECT
  l.id,
  l.node_id,
  n.name AS node_name,
  l.service,
  l.journal_cursor,
  l.message_hash,
  l.level,
  l.raw_message,
  l.observed_at,
  l.ingested_at
FROM system_logs l
JOIN nodes n ON n.id = l.node_id
ORDER BY l.observed_at DESC
LIMIT ?1
`

type ListRecentSystemLogsRow struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	NodeName      string         `json:"node_name"`
	Service       string         `json:"service"`
	JournalCursor sql.NullString `json:"journal_cursor"`
	MessageHash   string         `json:"message_hash"`
	Level         string         `json:"level"`
	RawMessage    string         `json:"raw_message"`
	ObservedAt    string         `json:"observed_at"`
	IngestedAt    string         `json:"ingested_at"`
}

func (q *Queries) ListRecentSystemLogs(ctx context.Context, limit int64) ([]ListRecentSystemLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSystemLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentSystemLogsRow
	for rows.Next() {
		var i ListRecentSystemLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.NodeName,
			&i.Service,
			&i.JournalCursor,
			&i.MessageHash,
			&i.Level,
			&i.RawMessage,
			&i.ObservedAt,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSystemLogsByNode = `-- name: ListRecentSystemLogsByNode :many
SELECT
  l.id,
  l.node_id,
  n.name AS node_name,
  l.service,
  l.journal_cursor,
  l.message_hash,
  l.level,
  l.raw_message,
  l.observed_at,
  l.ingested_at
FROM system_logs l
JOIN nodes n ON n.id = l.node_id
WHERE n.name = ?1
ORDER BY l.observed_at DESC
LIMIT ?2
`

type ListRecentSystemLogsByNodeParams struct {
	NodeName string `json:"node_name"`
	Limit    int64  `json:"limit"`
}

type ListRecentSystemLogsByNodeRow struct {
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	NodeName      string         `json:"node_name"`
	Service       string         `json:"service"`
	JournalCursor sql.NullString `json:"journal_cursor"`
	MessageHash   string         `json:"message_hash"`
	Level         string         `json:"level"`
	RawMessage    string         `json:"raw_message"`
	ObservedAt    string         `json:"observed_at"`
	IngestedAt    string         `json:"ingested_at"`
}

func (q *Queries) ListRecentSystemLogsByNode(ctx context.Context, arg ListRecentSystemLogsByNodeParams) ([]ListRecentSystemLogsByNodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSystemLogsByNode, arg.NodeName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentSystemLogsByNodeRow
	for rows.Next() {
		var i ListRecentSystemLogsByNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.NodeName,
			&i.Service,
			&i.JournalCursor,
			&i.MessageHash,
			&i.Level,
			&i.RawMessage,
			&i.ObservedAt,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
