// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traffic.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTrafficReport = `-- name: CreateTrafficReport :exec
INSERT INTO traffic_reports (
  id,
  node_id,
  sequence,
  agent_boot_id,
  reported_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
`

type CreateTrafficReportParams struct {
	ID          string `json:"id"`
	NodeID      string `json:"node_id"`
	Sequence    int64  `json:"sequence"`
	AgentBootID string `json:"agent_boot_id"`
	ReportedAt  string `json:"reported_at"`
}

func (q *Queries) CreateTrafficReport(ctx context.Context, arg CreateTrafficReportParams) error {
	_, err := q.db.ExecContext(ctx, createTrafficReport,
		arg.ID,
		arg.NodeID,
		arg.Sequence,
		arg.AgentBootID,
		arg.ReportedAt,
	)
	return err
}

const createTrafficUsageDelta = `-- name: CreateTrafficUsageDelta :exec
INSERT INTO traffic_usage_deltas (
  id,
  report_id,
  node_id,
  proxy_user_id,
  proxy_id,
  auth_name,
  direction,
  raw_bytes_delta,
  effective_multiplier,
  billable_bytes_delta,
  counter_value,
  counter_epoch,
  observed_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13
)
`

type CreateTrafficUsageDeltaParams struct {
	ID                  string         `json:"id"`
	ReportID            string         `json:"report_id"`
	NodeID              string         `json:"node_id"`
	ProxyUserID         string         `json:"proxy_user_id"`
	ProxyID             sql.NullString `json:"proxy_id"`
	AuthName            string         `json:"auth_name"`
	Direction           string         `json:"direction"`
	RawBytesDelta       int64          `json:"raw_bytes_delta"`
	EffectiveMultiplier float64        `json:"effective_multiplier"`
	BillableBytesDelta  int64          `json:"billable_bytes_delta"`
	CounterValue        int64          `json:"counter_value"`
	CounterEpoch        int64          `json:"counter_epoch"`
	ObservedAt          string         `json:"observed_at"`
}

func (q *Queries) CreateTrafficUsageDelta(ctx context.Context, arg CreateTrafficUsageDeltaParams) error {
	_, err := q.db.ExecContext(ctx, createTrafficUsageDelta,
		arg.ID,
		arg.ReportID,
		arg.NodeID,
		arg.ProxyUserID,
		arg.ProxyID,
		arg.AuthName,
		arg.Direction,
		arg.RawBytesDelta,
		arg.EffectiveMultiplier,
		arg.BillableBytesDelta,
		arg.CounterValue,
		arg.CounterEpoch,
		arg.ObservedAt,
	)
	return err
}

const getTrafficCredentialByNodeAuthName = `-- name: GetTrafficCredentialByNodeAuthName :one
SELECT
  c.proxy_user_id,
  c.proxy_id,
  COALESCE(c.traffic_multiplier, b.traffic_multiplier, p.traffic_multiplier, 1.0) AS effective_multiplier
FROM proxy_accesses c
JOIN proxies p ON p.id = c.proxy_id
JOIN nodes n ON n.id = p.node_id
JOIN user_node_bindings b ON b.proxy_user_id = c.proxy_user_id AND b.node_id = n.id
WHERE n.name = ?1
  AND c.auth_name = ?2
`

type GetTrafficCredentialByNodeAuthNameParams struct {
	NodeName string `json:"node_name"`
	AuthName string `json:"auth_name"`
}

type GetTrafficCredentialByNodeAuthNameRow struct {
	ProxyUserID         string  `json:"proxy_user_id"`
	ProxyID             string  `json:"proxy_id"`
	EffectiveMultiplier float64 `json:"effective_multiplier"`
}

func (q *Queries) GetTrafficCredentialByNodeAuthName(ctx context.Context, arg GetTrafficCredentialByNodeAuthNameParams) (GetTrafficCredentialByNodeAuthNameRow, error) {
	row := q.db.QueryRowContext(ctx, getTrafficCredentialByNodeAuthName, arg.NodeName, arg.AuthName)
	var i GetTrafficCredentialByNodeAuthNameRow
	err := row.Scan(&i.ProxyUserID, &i.ProxyID, &i.EffectiveMultiplier)
	return i, err
}

const getTrafficReportBySequence = `-- name: GetTrafficReportBySequence :one
SELECT
  id,
  node_id,
  sequence,
  agent_boot_id,
  reported_at,
  created_at
FROM traffic_reports
WHERE node_id = ?1
  AND agent_boot_id = ?2
  AND sequence = ?3
`

type GetTrafficReportBySequenceParams struct {
	NodeID      string `json:"node_id"`
	AgentBootID string `json:"agent_boot_id"`
	Sequence    int64  `json:"sequence"`
}

func (q *Queries) GetTrafficReportBySequence(ctx context.Context, arg GetTrafficReportBySequenceParams) (TrafficReport, error) {
	row := q.db.QueryRowContext(ctx, getTrafficReportBySequence, arg.NodeID, arg.AgentBootID, arg.Sequence)
	var i TrafficReport
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Sequence,
		&i.AgentBootID,
		&i.ReportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sumTrafficByAllUsers = `-- name: SumTrafficByAllUsers :many
SELECT
  u.name AS user_name,
  d.direction,
  d.raw_bytes,
  d.billable_bytes
FROM traffic_usage_totals d
JOIN proxy_users u ON u.id = d.proxy_user_id
WHERE u.deleted_at IS NULL
ORDER BY u.name, d.direction
`

type SumTrafficByAllUsersRow struct {
	UserName      string `json:"user_name"`
	Direction     string `json:"direction"`
	RawBytes      int64  `json:"raw_bytes"`
	BillableBytes int64  `json:"billable_bytes"`
}

func (q *Queries) SumTrafficByAllUsers(ctx context.Context) ([]SumTrafficByAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, sumTrafficByAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumTrafficByAllUsersRow
	for rows.Next() {
		var i SumTrafficByAllUsersRow
		if err := rows.Scan(
			&i.UserName,
			&i.Direction,
			&i.RawBytes,
			&i.BillableBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTrafficByUser = `-- name: SumTrafficByUser :many
SELECT
  u.name AS user_name,
  d.direction,
  d.raw_bytes,
  d.billable_bytes
FROM traffic_usage_totals d
JOIN proxy_users u ON u.id = d.proxy_user_id
WHERE u.name = ?1
  AND u.deleted_at IS NULL
ORDER BY d.direction
`

type SumTrafficByUserRow struct {
	UserName      string `json:"user_name"`
	Direction     string `json:"direction"`
	RawBytes      int64  `json:"raw_bytes"`
	BillableBytes int64  `json:"billable_bytes"`
}

func (q *Queries) SumTrafficByUser(ctx context.Context, userName string) ([]SumTrafficByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, sumTrafficByUser, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumTrafficByUserRow
	for rows.Next() {
		var i SumTrafficByUserRow
		if err := rows.Scan(
			&i.UserName,
			&i.Direction,
			&i.RawBytes,
			&i.BillableBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrafficUsageTotal = `-- name: UpsertTrafficUsageTotal :exec
INSERT INTO traffic_usage_totals (
  proxy_user_id,
  direction,
  raw_bytes,
  billable_bytes
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
ON CONFLICT(proxy_user_id, direction) DO UPDATE SET
  raw_bytes = traffic_usage_totals.raw_bytes + excluded.raw_bytes,
  billable_bytes = traffic_usage_totals.billable_bytes + excluded.billable_bytes,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertTrafficUsageTotalParams struct {
	ProxyUserID        string `json:"proxy_user_id"`
	Direction          string `json:"direction"`
	RawBytesDelta      int64  `json:"raw_bytes_delta"`
	BillableBytesDelta int64  `json:"billable_bytes_delta"`
}

func (q *Queries) UpsertTrafficUsageTotal(ctx context.Context, arg UpsertTrafficUsageTotalParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrafficUsageTotal,
		arg.ProxyUserID,
		arg.Direction,
		arg.RawBytesDelta,
		arg.BillableBytesDelta,
	)
	return err
}
