// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProxyUser = `-- name: CreateProxyUser :exec
INSERT INTO proxy_users (
  id,
  name,
  display_name,
  global_quota_bytes,
  expire_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
`

type CreateProxyUserParams struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	DisplayName      string         `json:"display_name"`
	GlobalQuotaBytes int64          `json:"global_quota_bytes"`
	ExpireAt         sql.NullString `json:"expire_at"`
}

func (q *Queries) CreateProxyUser(ctx context.Context, arg CreateProxyUserParams) error {
	_, err := q.db.ExecContext(ctx, createProxyUser,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.GlobalQuotaBytes,
		arg.ExpireAt,
	)
	return err
}

const getProxyUserByName = `-- name: GetProxyUserByName :one
SELECT
  id,
  name,
  display_name,
  status,
  global_quota_bytes,
  expire_at,
  created_at,
  updated_at
FROM proxy_users
WHERE name = ?1
`

func (q *Queries) GetProxyUserByName(ctx context.Context, name string) (ProxyUser, error) {
	row := q.db.QueryRowContext(ctx, getProxyUserByName, name)
	var i ProxyUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.GlobalQuotaBytes,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyUsers = `-- name: ListProxyUsers :many
SELECT
  id,
  name,
  display_name,
  status,
  global_quota_bytes,
  expire_at,
  created_at,
  updated_at
FROM proxy_users
ORDER BY name
`

func (q *Queries) ListProxyUsers(ctx context.Context) ([]ProxyUser, error) {
	rows, err := q.db.QueryContext(ctx, listProxyUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyUser
	for rows.Next() {
		var i ProxyUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Status,
			&i.GlobalQuotaBytes,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyUsersWithProxyCounts = `-- name: ListProxyUsersWithProxyCounts :many
SELECT
  u.id,
  u.name,
  u.display_name,
  u.status,
  u.global_quota_bytes,
  u.expire_at,
  u.created_at,
  u.updated_at,
  COUNT(a.id) AS proxy_count
FROM proxy_users u
LEFT JOIN proxy_accesses a ON a.proxy_user_id = u.id
GROUP BY
  u.id,
  u.name,
  u.display_name,
  u.status,
  u.global_quota_bytes,
  u.expire_at,
  u.created_at,
  u.updated_at
ORDER BY u.name
`

type ListProxyUsersWithProxyCountsRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	DisplayName      string         `json:"display_name"`
	Status           string         `json:"status"`
	GlobalQuotaBytes int64          `json:"global_quota_bytes"`
	ExpireAt         sql.NullString `json:"expire_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	ProxyCount       int64          `json:"proxy_count"`
}

func (q *Queries) ListProxyUsersWithProxyCounts(ctx context.Context) ([]ListProxyUsersWithProxyCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProxyUsersWithProxyCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProxyUsersWithProxyCountsRow
	for rows.Next() {
		var i ListProxyUsersWithProxyCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Status,
			&i.GlobalQuotaBytes,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProxyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProxyUserExpire = `-- name: SetProxyUserExpire :execrows
UPDATE proxy_users
SET
  expire_at = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?2
`

type SetProxyUserExpireParams struct {
	ExpireAt sql.NullString `json:"expire_at"`
	Name     string         `json:"name"`
}

func (q *Queries) SetProxyUserExpire(ctx context.Context, arg SetProxyUserExpireParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProxyUserExpire, arg.ExpireAt, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProxyUserQuota = `-- name: SetProxyUserQuota :execrows
UPDATE proxy_users
SET
  global_quota_bytes = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?2
`

type SetProxyUserQuotaParams struct {
	GlobalQuotaBytes int64  `json:"global_quota_bytes"`
	Name             string `json:"name"`
}

func (q *Queries) SetProxyUserQuota(ctx context.Context, arg SetProxyUserQuotaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProxyUserQuota, arg.GlobalQuotaBytes, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProxyUserStatus = `-- name: SetProxyUserStatus :execrows
UPDATE proxy_users
SET
  status = ?1,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE name = ?2
`

type SetProxyUserStatusParams struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

func (q *Queries) SetProxyUserStatus(ctx context.Context, arg SetProxyUserStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProxyUserStatus, arg.Status, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
