// Trimmed vendored copy of sing-box's daemon gRPC contract.
//
// Upstream:  github.com/SagerNet/sing-box
// File:      daemon/started_service.proto
// Tag:       v1.14.0-beta.2
// Commit:    03c3bf4c01e7b1fd165d0c46ff376828fa878aab
//
// Only the connection-subscription surface is vendored. See README.md for the
// trimming rationale, the regeneration commands, and the re-verification
// procedure for a new upstream tag.
//
// Wire compatibility is preserved by keeping the proto package (`daemon`), the
// service name (`StartedService`), the method name, and every field number and
// type exactly as upstream declares them. gRPC routes on the fully-qualified
// method name `/daemon.StartedService/SubscribeConnections`, and proto3 binary
// encoding carries field numbers rather than names, so omitting the other RPCs
// is invisible to the server.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: daemonpb/singbox_daemon_connections.proto

package daemonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StartedService_SubscribeConnections_FullMethodName = "/daemon.StartedService/SubscribeConnections"
)

// StartedServiceClient is the client API for StartedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StartedService is deliberately declared with one RPC. Upstream's service has
// 34, including a control plane BoxFleet must never reach: StopService,
// ReloadService, CloseConnection, CloseAllConnections, SelectOutbound and
// TriggerDebugCrash. They are omitted from the descriptor so no generated
// client method exists for them and no BoxFleet code can call one by accident.
type StartedServiceClient interface {
	// SubscribeConnections streams connection lifecycle events.
	//
	// The first message always carries reset=true and the full current state:
	// every live connection plus every entry still held in the closed-connection
	// ring, all as CONNECTION_EVENT_NEW (see buildInitialConnectionState,
	// daemon/started_service.go:790-820). Closed replays are distinguishable by a
	// non-zero Connection.closedAt.
	//
	// The server waits for the box instance to reach STARTED before the first
	// send, and fails with Unimplemented when connection tracking is off.
	SubscribeConnections(ctx context.Context, in *SubscribeConnectionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionEvents], error)
}

type startedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStartedServiceClient(cc grpc.ClientConnInterface) StartedServiceClient {
	return &startedServiceClient{cc}
}

func (c *startedServiceClient) SubscribeConnections(ctx context.Context, in *SubscribeConnectionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionEvents], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StartedService_ServiceDesc.Streams[0], StartedService_SubscribeConnections_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeConnectionsRequest, ConnectionEvents]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StartedService_SubscribeConnectionsClient = grpc.ServerStreamingClient[ConnectionEvents]

// StartedServiceServer is the server API for StartedService service.
// All implementations must embed UnimplementedStartedServiceServer
// for forward compatibility.
//
// StartedService is deliberately declared with one RPC. Upstream's service has
// 34, including a control plane BoxFleet must never reach: StopService,
// ReloadService, CloseConnection, CloseAllConnections, SelectOutbound and
// TriggerDebugCrash. They are omitted from the descriptor so no generated
// client method exists for them and no BoxFleet code can call one by accident.
type StartedServiceServer interface {
	// SubscribeConnections streams connection lifecycle events.
	//
	// The first message always carries reset=true and the full current state:
	// every live connection plus every entry still held in the closed-connection
	// ring, all as CONNECTION_EVENT_NEW (see buildInitialConnectionState,
	// daemon/started_service.go:790-820). Closed replays are distinguishable by a
	// non-zero Connection.closedAt.
	//
	// The server waits for the box instance to reach STARTED before the first
	// send, and fails with Unimplemented when connection tracking is off.
	SubscribeConnections(*SubscribeConnectionsRequest, grpc.ServerStreamingServer[ConnectionEvents]) error
	mustEmbedUnimplementedStartedServiceServer()
}

// UnimplementedStartedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStartedServiceServer struct{}

func (UnimplementedStartedServiceServer) SubscribeConnections(*SubscribeConnectionsRequest, grpc.ServerStreamingServer[ConnectionEvents]) error {
	return status.Error(codes.Unimplemented, "method SubscribeConnections not implemented")
}
func (UnimplementedStartedServiceServer) mustEmbedUnimplementedStartedServiceServer() {}
func (UnimplementedStartedServiceServer) testEmbeddedByValue()                        {}

// UnsafeStartedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StartedServiceServer will
// result in compilation errors.
type UnsafeStartedServiceServer interface {
	mustEmbedUnimplementedStartedServiceServer()
}

func RegisterStartedServiceServer(s grpc.ServiceRegistrar, srv StartedServiceServer) {
	// If the following call panics, it indicates UnimplementedStartedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StartedService_ServiceDesc, srv)
}

func _StartedService_SubscribeConnections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeConnectionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StartedServiceServer).SubscribeConnections(m, &grpc.GenericServerStream[SubscribeConnectionsRequest, ConnectionEvents]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StartedService_SubscribeConnectionsServer = grpc.ServerStreamingServer[ConnectionEvents]

// StartedService_ServiceDesc is the grpc.ServiceDesc for StartedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StartedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.StartedService",
	HandlerType: (*StartedServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeConnections",
			Handler:       _StartedService_SubscribeConnections_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemonpb/singbox_daemon_connections.proto",
}
